openapi: 3.0.3

info:
  title: SUGDiO API 
  description: API Specification for SUGDiO API
  version: 0.0.1

tags:
  - name: employee
    description: Manage employees
  - name: vacation
    description: Manage vacations
  - name: shift
    description: Manage shifts
  - name: shift_type
    description: Manage shift types

paths:
  /employee/{employeeID}:
    get:
      tags:
        - employee
      summary: Get employee
      operationId: getEmployee

      parameters:
        - name: employeeID
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
      
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/Employee'

        "404":
          $ref: '#/components/responses/NotFound'
        
        "401":
          $ref: '#/components/responses/Unauthorized'

        "403":
          $ref: '#/components/responses/Forbidden'
    
    patch:
      tags:
        - employee
      summary: Patch employee
      operationId: patchEmployee

      parameters:
        - name: employeeID
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1      
      
      requestBody:
        description: Employee field to patch
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmployeePatch'
      
      responses:
        "200":
          description: Employee updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'

        "400":
          $ref: '#/components/responses/BadRequest'
        
        "401":
          $ref: '#/components/responses/Unauthorized'
        
        "403":
          $ref: '#/components/responses/Forbidden'
        
        "404":
          $ref: '#/components/responses/NotFound'

    delete:
      tags:
        - employee
      summary: Delete employee
      operationId: deleteEmployee

      parameters:
        - name: employeeID
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1 
      
      responses:
        "204":
          description: Employee deleted

        "404":
          $ref: '#/components/responses/NotFound'
        
        "409":
          $ref: "#/components/responses/Conflict"

        "401":
          $ref: '#/components/responses/Unauthorized'
        
        "403":
          $ref: '#/components/responses/Forbidden'   



  /employee:
    get:
      tags:
        - employee
      summary: Get all employees
      operationId: getEmployees
      
      parameters:
        - name: filter
          description: Employees filter
          in: query
          required: false
          explode: true 
          schema:
            $ref: '#/components/schemas/EmployeeFilter'

      responses:
        "200":
          description: Success
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/EmployeeList'

        "401":
          $ref: '#/components/responses/Unauthorized'

        "403":
          $ref: '#/components/responses/Forbidden'

    
    post:
      tags:
        - employee
      summary: Create employee 
      operationId: createEmployee

      requestBody:
        description: New employee data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmployeeCreate'

      responses:
        "201":
          description: Employee created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'

        "400":
          $ref: '#/components/responses/BadRequest'
        
        "401":
          $ref: '#/components/responses/Unauthorized'
        
        "403":
          $ref: '#/components/responses/Forbidden'
  




  /shift:
    post:
      tags:
        - shift
      summary: Create shift 
      operationId: createShift

      requestBody:
        description: New shift data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ShiftCreate'

      responses:
        "201":
          description: Shift created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Shift'

        "400":
          $ref: '#/components/responses/BadRequest'
        
        "401":
          $ref: '#/components/responses/Unauthorized'
        
        "403":
          $ref: '#/components/responses/Forbidden'
    
    get:
      tags:
        - shift
      summary: Get all shifts
      operationId: getShifts
      
      parameters:
        - name: filter
          description: Shifts filter
          in: query
          required: false
          explode: true 
          schema:
            $ref: '#/components/schemas/ShiftFilter'

      responses:
        "200":
          description: Success
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/ShiftList'

        "401":
          $ref: '#/components/responses/Unauthorized'

        "403":
          $ref: '#/components/responses/Forbidden'


  /shift/{shiftID}:
    get:
      tags:
        - shift
      summary: Get shift
      operationId: getShift

      parameters:
        - name: shiftID
          in: path
          required: true
          schema:
            type: integer
            minimum: 1
      
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/Shift'

        "404":
          $ref: '#/components/responses/NotFound'
        
        "401":
          $ref: '#/components/responses/Unauthorized'

        "403":
          $ref: '#/components/responses/Forbidden'


    patch:
      tags:
        - shift
      summary: Patch shift
      operationId: patchShift

      parameters:
        - name: shiftID
          in: path
          required: true
          schema:
            type: integer
            minimum: 1      
      
      requestBody:
        description: Shift fields to patch
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ShiftPatch'
      
      responses:
        "200":
          description: Shift updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Shift'

        "400":
          $ref: '#/components/responses/BadRequest'
        
        "401":
          $ref: '#/components/responses/Unauthorized'
        
        "403":
          $ref: '#/components/responses/Forbidden'
        
        "404":
          $ref: '#/components/responses/NotFound'

    delete:
      tags:
        - shift
      summary: Delete shift
      operationId: deleteShift

      parameters:
        - name: shiftID
          in: path
          required: true
          schema:
            type: integer
            minimum: 1 
      
      responses:
        "204":
          description: Shift deleted

        "404":
          $ref: '#/components/responses/NotFound'
        
        "409":
          $ref: "#/components/responses/Conflict"

        "401":
          $ref: '#/components/responses/Unauthorized'
        
        "403":
          $ref: '#/components/responses/Forbidden'  

  /shift-type:
    post: 
      tags:
        - shift_type
      summary: Create shift type
      operationId: createShiftType

      requestBody:
        description: New shift type data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ShiftTypeCreate'

      responses:
        "201":
          description: Shift type created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShiftType'

        "400":
          $ref: '#/components/responses/BadRequest'
        
        "401":
          $ref: '#/components/responses/Unauthorized'
        
        "403":
          $ref: '#/components/responses/Forbidden'
  
    get:
      tags:
        - shift_type
      summary: Get all shift types
      operationId: getShiftTypes

      responses:
        "200":
          description: Success
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/ShiftTypeList'

        "401":
          $ref: '#/components/responses/Unauthorized'

        "403":
          $ref: '#/components/responses/Forbidden'

  /shift-type/{shiftTypeID}:
    get:
      tags:
        - shift_type
      summary: Get shift type
      operationId: getShiftType

      parameters:
        - name: shiftTypeID
          in: path
          required: true
          schema:
            type: integer
            minimum: 1
      
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/ShiftType'

        "404":
          $ref: '#/components/responses/NotFound'
        
        "401":
          $ref: '#/components/responses/Unauthorized'

        "403":
          $ref: '#/components/responses/Forbidden'


    patch:
      tags:
        - shift_type
      summary: Patch shift type
      operationId: patchShiftType

      parameters:
        - name: shiftTypeID
          in: path
          required: true
          schema:
            type: integer
            minimum: 1      
      
      requestBody:
        description: Shift type fields to patch
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ShiftTypePatch'
      
      responses:
        "200":
          description: Shift type updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShiftType'

        "400":
          $ref: '#/components/responses/BadRequest'
        
        "401":
          $ref: '#/components/responses/Unauthorized'
        
        "403":
          $ref: '#/components/responses/Forbidden'
        
        "404":
          $ref: '#/components/responses/NotFound'

    delete:
      tags:
        - shift_type
      summary: Delete shift type
      operationId: deleteShiftType

      parameters:
        - name: shiftTypeID
          in: path
          required: true
          schema:
            type: integer
            minimum: 1 
      
      responses:
        "204":
          description: Shift type deleted

        "404":
          $ref: '#/components/responses/NotFound'
        
        "409":
          $ref: "#/components/responses/Conflict"

        "401":
          $ref: '#/components/responses/Unauthorized'
        
        "403":
          $ref: '#/components/responses/Forbidden'  

components:
  responses:
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
            
    Forbidden:
      description: Insufficient privileges
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    NotFound:
      description: Object not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    
    Conflict:
      description: Conflict":" Object has related data
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    
    BadRequest:
      description: Error in request params/body
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  schemas:
    Error:
      type: object
      required:
        - message
        - code
      properties:
        message:
          type: string
          example: "Employee not found"
        code:
          type: string
          example: "EMPLOYEE_NOT_FOUND"
    
    EmployeeBase:
      type: object
      required:
        - first_name
        - second_name
      properties:
        first_name:
          type: string
        middle_name:
          type: string
          nullable: true
        second_name:
          type: string
        active:
          type: boolean

    EmployeeCreate:
      allOf:
        - $ref: '#/components/schemas/EmployeeBase'
        - type: object
          properties:
            position_id:
              type: integer
              nullable: true
            department_id:
              type: integer
              nullable: true
            user_id:
              type: integer
              format: int64
              nullable: true
    
    EmployeePatch:
      type: object
      properties:
        first_name:
          type: string
        middle_name:
          type: string
        second_name:
          type: string
        position_id:
          type: integer
          nullable: true
        department_id:
          type: integer
          nullable: true
        active:
          type: boolean
        user_id:
          type: integer
          nullable: true
          format: int64
    
    Employee:
      allOf:
        - type: object
          required:
            - id
          properties:
            id:
              type: integer
              format: int64
            created_at:
                type: string
                format: date-time
                example: '2024-03-20T09:12:28Z'
            
            department: 
              $ref: '#/components/schemas/DepartmentShort'
            position: 
              $ref: '#/components/schemas/PositionShort'
            user: 
              $ref: '#/components/schemas/UserShort'

        - $ref: '#/components/schemas/EmployeeBase'

    EmployeeFilter:
      type: object
      properties:
        first_name:
          type: string
          nullable: true
        second_name:
          type: string
          nullable: true
        active:
          type: boolean
          nullable: true
        department_id:
          type: integer
          nullable: true
        limit:
          type: integer
          nullable: true
        offset:
          type: integer
          nullable: true

    EmployeeList:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Employee'
        total:
          type: integer
          example: 100
    
    EmployeeShort:
      type: object
      allOf:
        - $ref: '#/components/schemas/EmployeeBase'
        - type: object
          required:
            - id
          properties:
            id:
              type: integer
              format: int64
    
    UserShort:
      type: object
      nullable: true
      required:
        - id
        - email
        - role 
      properties:
        id:
          type: integer
        email:
          type: string
        role:
          example: "admin/manager/employee"
          type: string
    
    DepartmentShort:
      type: object
      nullable: true
      required:
        - id
        - name
      properties:
        id:
          type: integer
        name: 
          type: string
    
    PositionShort:
      type: object
      nullable: true
      required:
        - id
        - name
      properties:
        id:
          type: integer
        name:
          type: string
    
    ShiftBase:
      type: object
      required:
        - date
      properties:
        date:
          type: string
          format: date
        status:
          type: string
          example: "planned/completed/cancelled"
    
    ShiftCreate:
      type: object
      required:
        - employee_id
        - date
        - shift_type_id
      allOf:
        - $ref: '#/components/schemas/ShiftBase'
        - type: object
          properties:
            shift_type_id:
              type: integer
            employee_id:
              type: integer
              format: int64
    
    ShiftTypeCreate:
      type: object
      required:
        - name
      properties:
        name: 
          type: string

    ShiftTypePatch:
      type: object
      properties:
        name:
          type: string

    ShiftType:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
    
    ShiftTypeList:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/ShiftType'
        total:
          type: integer
          example: 100

    Shift:
      allOf:
        - type: object
          required:
            - id
          properties:
            id:
              type: integer
            created_at:
                type: string
                format: date-time
                example: '2024-03-20T09:12:28Z'
            updated_at:
                type: string
                format: date-time
                example: '2024-03-20T09:12:28Z'
            shift_type:
              $ref: '#/components/schemas/ShiftType'
            employee:
              $ref: '#/components/schemas/EmployeeShort'

        - $ref: '#/components/schemas/ShiftBase'

    ShiftList:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Shift'
        total:
          type: integer
          example: 100
    
    ShiftFilter:
      type: object
      properties:
        shift_type_id:
          type: integer
          nullable: true
        date_from:
          type: string
          format: date
          nullable: true
        date_to:
          type: string
          format: date
          nullable: true
        status:
          type: string
          nullable: true
        employee_id:
          type: integer
          nullable: true
        limit:
          type: integer
          nullable: true
        offset:
          type: integer
          nullable: true
    
    ShiftPatch:
      type: object
      properties:
        shift_type_id:
          type: integer
          nullable: true
        date:
          type: string
          nullable: true
          format: date
        status: 
          type: string
          nullable: true
        employee_id:
          type: integer
          nullable: true