// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// DepartmentShort defines model for DepartmentShort.
type DepartmentShort struct {
	Id   int    `json:"id"`
	Name string `json:"name"`
}

// Employee defines model for Employee.
type Employee struct {
	Active     *bool            `json:"active,omitempty"`
	CreatedAt  *time.Time       `json:"created_at,omitempty"`
	Department *DepartmentShort `json:"department,omitempty"`
	FirstName  string           `json:"first_name"`
	Id         int64            `json:"id"`
	MiddleName *string          `json:"middle_name,omitempty"`
	Position   *PositionShort   `json:"position,omitempty"`
	SecondName string           `json:"second_name"`
	User       *UserShort       `json:"user,omitempty"`
}

// EmployeeBase defines model for EmployeeBase.
type EmployeeBase struct {
	Active     *bool   `json:"active,omitempty"`
	FirstName  string  `json:"first_name"`
	MiddleName *string `json:"middle_name,omitempty"`
	SecondName string  `json:"second_name"`
}

// EmployeeCreate defines model for EmployeeCreate.
type EmployeeCreate struct {
	Active       *bool   `json:"active,omitempty"`
	DepartmentId *int    `json:"department_id,omitempty"`
	FirstName    string  `json:"first_name"`
	MiddleName   *string `json:"middle_name,omitempty"`
	PositionId   *int    `json:"position_id,omitempty"`
	SecondName   string  `json:"second_name"`
	UserId       *int64  `json:"user_id,omitempty"`
}

// EmployeeFilter defines model for EmployeeFilter.
type EmployeeFilter struct {
	Active       *bool   `json:"active,omitempty"`
	DepartmentId *int    `json:"department_id,omitempty"`
	FirstName    *string `json:"first_name,omitempty"`
	Limit        *int    `json:"limit,omitempty"`
	Offset       *int    `json:"offset,omitempty"`
	SecondName   *string `json:"second_name,omitempty"`
}

// EmployeeList defines model for EmployeeList.
type EmployeeList struct {
	Items *[]Employee `json:"items,omitempty"`
	Total *int        `json:"total,omitempty"`
}

// EmployeePatch defines model for EmployeePatch.
type EmployeePatch struct {
	Active       *bool   `json:"active,omitempty"`
	DepartmentId *int    `json:"department_id,omitempty"`
	FirstName    *string `json:"first_name,omitempty"`
	MiddleName   *string `json:"middle_name,omitempty"`
	PositionId   *int    `json:"position_id,omitempty"`
	SecondName   *string `json:"second_name,omitempty"`
	UserId       *int64  `json:"user_id,omitempty"`
}

// EmployeeShort defines model for EmployeeShort.
type EmployeeShort struct {
	Active     *bool   `json:"active,omitempty"`
	FirstName  string  `json:"first_name"`
	Id         int64   `json:"id"`
	MiddleName *string `json:"middle_name,omitempty"`
	SecondName string  `json:"second_name"`
}

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// PositionShort defines model for PositionShort.
type PositionShort struct {
	Id   int    `json:"id"`
	Name string `json:"name"`
}

// Shift defines model for Shift.
type Shift struct {
	CreatedAt *time.Time         `json:"created_at,omitempty"`
	Date      openapi_types.Date `json:"date"`
	Employee  *EmployeeShort     `json:"employee,omitempty"`
	Id        int                `json:"id"`
	ShiftType *ShiftType         `json:"shift_type,omitempty"`
	Status    *string            `json:"status,omitempty"`
	UpdatedAt *time.Time         `json:"updated_at,omitempty"`
}

// ShiftBase defines model for ShiftBase.
type ShiftBase struct {
	Date   openapi_types.Date `json:"date"`
	Status *string            `json:"status,omitempty"`
}

// ShiftCreate defines model for ShiftCreate.
type ShiftCreate struct {
	Date        openapi_types.Date `json:"date"`
	EmployeeId  *int64             `json:"employee_id,omitempty"`
	ShiftTypeId *int               `json:"shift_type_id,omitempty"`
	Status      *string            `json:"status,omitempty"`
}

// ShiftFilter defines model for ShiftFilter.
type ShiftFilter struct {
	DateFrom    *openapi_types.Date `json:"date_from,omitempty"`
	DateTo      *openapi_types.Date `json:"date_to,omitempty"`
	EmployeeId  *int                `json:"employee_id,omitempty"`
	Limit       *int                `json:"limit,omitempty"`
	Offset      *int                `json:"offset,omitempty"`
	ShiftTypeId *int                `json:"shift_type_id,omitempty"`
	Status      *string             `json:"status,omitempty"`
}

// ShiftList defines model for ShiftList.
type ShiftList struct {
	Items *[]Shift `json:"items,omitempty"`
	Total *int     `json:"total,omitempty"`
}

// ShiftPatch defines model for ShiftPatch.
type ShiftPatch struct {
	Date        *openapi_types.Date `json:"date,omitempty"`
	EmployeeId  *int                `json:"employee_id,omitempty"`
	ShiftTypeId *int                `json:"shift_type_id,omitempty"`
	Status      *string             `json:"status,omitempty"`
}

// ShiftType defines model for ShiftType.
type ShiftType struct {
	Id   *int    `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

// ShiftTypeCreate defines model for ShiftTypeCreate.
type ShiftTypeCreate struct {
	Name string `json:"name"`
}

// ShiftTypeList defines model for ShiftTypeList.
type ShiftTypeList struct {
	Items *[]ShiftType `json:"items,omitempty"`
	Total *int         `json:"total,omitempty"`
}

// ShiftTypePatch defines model for ShiftTypePatch.
type ShiftTypePatch struct {
	Name *string `json:"name,omitempty"`
}

// UserShort defines model for UserShort.
type UserShort struct {
	Email string `json:"email"`
	Id    int    `json:"id"`
	Role  string `json:"role"`
}

// Vacation defines model for Vacation.
type Vacation struct {
	Comment   *string             `json:"comment,omitempty"`
	CreatedAt *time.Time          `json:"created_at,omitempty"`
	Employee  *EmployeeShort      `json:"employee,omitempty"`
	EndDate   *openapi_types.Date `json:"end_date,omitempty"`
	Id        int                 `json:"id"`
	StartDate *openapi_types.Date `json:"start_date,omitempty"`
	Status    string              `json:"status"`
	UpdatedAt *time.Time          `json:"updated_at,omitempty"`
}

// VacationBase defines model for VacationBase.
type VacationBase struct {
	Comment   *string             `json:"comment,omitempty"`
	EndDate   *openapi_types.Date `json:"end_date,omitempty"`
	StartDate *openapi_types.Date `json:"start_date,omitempty"`
}

// VacationCreate defines model for VacationCreate.
type VacationCreate struct {
	Comment    *string             `json:"comment,omitempty"`
	EmployeeId *int                `json:"employee_id,omitempty"`
	EndDate    *openapi_types.Date `json:"end_date,omitempty"`
	StartDate  *openapi_types.Date `json:"start_date,omitempty"`
}

// VacationFilter defines model for VacationFilter.
type VacationFilter struct {
	DateFrom   *openapi_types.Date `json:"date_from,omitempty"`
	DateTo     *openapi_types.Date `json:"date_to,omitempty"`
	EmployeeId *int                `json:"employee_id,omitempty"`
	Limit      *int                `json:"limit,omitempty"`
	Offset     *int                `json:"offset,omitempty"`
	Status     *string             `json:"status,omitempty"`
}

// VacationList defines model for VacationList.
type VacationList struct {
	Items *[]Vacation `json:"items,omitempty"`
	Total *int        `json:"total,omitempty"`
}

// VacationPatch defines model for VacationPatch.
type VacationPatch struct {
	Comment   *string             `json:"comment,omitempty"`
	EndDate   *openapi_types.Date `json:"end_date,omitempty"`
	StartDate *openapi_types.Date `json:"start_date,omitempty"`
	Status    *string             `json:"status,omitempty"`
}

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// GetEmployeesParams defines parameters for GetEmployees.
type GetEmployeesParams struct {
	// Filter Employees filter
	Filter *EmployeeFilter `form:"filter,omitempty" json:"filter,omitempty"`
}

// GetShiftsParams defines parameters for GetShifts.
type GetShiftsParams struct {
	// Filter Shifts filter
	Filter *ShiftFilter `form:"filter,omitempty" json:"filter,omitempty"`
}

// GetVacationsParams defines parameters for GetVacations.
type GetVacationsParams struct {
	// Filter Vacations filter
	Filter *VacationFilter `form:"filter,omitempty" json:"filter,omitempty"`
}

// CreateEmployeeJSONRequestBody defines body for CreateEmployee for application/json ContentType.
type CreateEmployeeJSONRequestBody = EmployeeCreate

// PatchEmployeeJSONRequestBody defines body for PatchEmployee for application/json ContentType.
type PatchEmployeeJSONRequestBody = EmployeePatch

// CreateShiftJSONRequestBody defines body for CreateShift for application/json ContentType.
type CreateShiftJSONRequestBody = ShiftCreate

// CreateShiftTypeJSONRequestBody defines body for CreateShiftType for application/json ContentType.
type CreateShiftTypeJSONRequestBody = ShiftTypeCreate

// PatchShiftTypeJSONRequestBody defines body for PatchShiftType for application/json ContentType.
type PatchShiftTypeJSONRequestBody = ShiftTypePatch

// PatchShiftJSONRequestBody defines body for PatchShift for application/json ContentType.
type PatchShiftJSONRequestBody = ShiftPatch

// CreateVacationJSONRequestBody defines body for CreateVacation for application/json ContentType.
type CreateVacationJSONRequestBody = VacationCreate

// PatchVacationJSONRequestBody defines body for PatchVacation for application/json ContentType.
type PatchVacationJSONRequestBody = VacationPatch

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get all employees
	// (GET /employee)
	GetEmployees(w http.ResponseWriter, r *http.Request, params GetEmployeesParams)
	// Create employee
	// (POST /employee)
	CreateEmployee(w http.ResponseWriter, r *http.Request)
	// Delete employee
	// (DELETE /employee/{employeeID})
	DeleteEmployee(w http.ResponseWriter, r *http.Request, employeeID int64)
	// Get employee
	// (GET /employee/{employeeID})
	GetEmployee(w http.ResponseWriter, r *http.Request, employeeID int64)
	// Patch employee
	// (PATCH /employee/{employeeID})
	PatchEmployee(w http.ResponseWriter, r *http.Request, employeeID int64)
	// Get all shifts
	// (GET /shift)
	GetShifts(w http.ResponseWriter, r *http.Request, params GetShiftsParams)
	// Create shift
	// (POST /shift)
	CreateShift(w http.ResponseWriter, r *http.Request)
	// Get all shift types
	// (GET /shift-type)
	GetShiftTypes(w http.ResponseWriter, r *http.Request)
	// Create shift type
	// (POST /shift-type)
	CreateShiftType(w http.ResponseWriter, r *http.Request)
	// Delete shift type
	// (DELETE /shift-type/{shiftTypeID})
	DeleteShiftType(w http.ResponseWriter, r *http.Request, shiftTypeID int)
	// Get shift type
	// (GET /shift-type/{shiftTypeID})
	GetShiftType(w http.ResponseWriter, r *http.Request, shiftTypeID int)
	// Patch shift type
	// (PATCH /shift-type/{shiftTypeID})
	PatchShiftType(w http.ResponseWriter, r *http.Request, shiftTypeID int)
	// Delete shift
	// (DELETE /shift/{shiftID})
	DeleteShift(w http.ResponseWriter, r *http.Request, shiftID int)
	// Get shift
	// (GET /shift/{shiftID})
	GetShift(w http.ResponseWriter, r *http.Request, shiftID int)
	// Patch shift
	// (PATCH /shift/{shiftID})
	PatchShift(w http.ResponseWriter, r *http.Request, shiftID int)
	// Get all vacations
	// (GET /vacation)
	GetVacations(w http.ResponseWriter, r *http.Request, params GetVacationsParams)
	// Create vacation
	// (POST /vacation)
	CreateVacation(w http.ResponseWriter, r *http.Request)
	// Delete vacation
	// (DELETE /vacation/{vacationID})
	DeleteVacation(w http.ResponseWriter, r *http.Request, vacationID int)
	// Get vacation
	// (GET /vacation/{vacationID})
	GetVacation(w http.ResponseWriter, r *http.Request, vacationID int)
	// Patch vacation
	// (PATCH /vacation/{vacationID})
	PatchVacation(w http.ResponseWriter, r *http.Request, vacationID int)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Get all employees
// (GET /employee)
func (_ Unimplemented) GetEmployees(w http.ResponseWriter, r *http.Request, params GetEmployeesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create employee
// (POST /employee)
func (_ Unimplemented) CreateEmployee(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete employee
// (DELETE /employee/{employeeID})
func (_ Unimplemented) DeleteEmployee(w http.ResponseWriter, r *http.Request, employeeID int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get employee
// (GET /employee/{employeeID})
func (_ Unimplemented) GetEmployee(w http.ResponseWriter, r *http.Request, employeeID int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Patch employee
// (PATCH /employee/{employeeID})
func (_ Unimplemented) PatchEmployee(w http.ResponseWriter, r *http.Request, employeeID int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get all shifts
// (GET /shift)
func (_ Unimplemented) GetShifts(w http.ResponseWriter, r *http.Request, params GetShiftsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create shift
// (POST /shift)
func (_ Unimplemented) CreateShift(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get all shift types
// (GET /shift-type)
func (_ Unimplemented) GetShiftTypes(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create shift type
// (POST /shift-type)
func (_ Unimplemented) CreateShiftType(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete shift type
// (DELETE /shift-type/{shiftTypeID})
func (_ Unimplemented) DeleteShiftType(w http.ResponseWriter, r *http.Request, shiftTypeID int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get shift type
// (GET /shift-type/{shiftTypeID})
func (_ Unimplemented) GetShiftType(w http.ResponseWriter, r *http.Request, shiftTypeID int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Patch shift type
// (PATCH /shift-type/{shiftTypeID})
func (_ Unimplemented) PatchShiftType(w http.ResponseWriter, r *http.Request, shiftTypeID int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete shift
// (DELETE /shift/{shiftID})
func (_ Unimplemented) DeleteShift(w http.ResponseWriter, r *http.Request, shiftID int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get shift
// (GET /shift/{shiftID})
func (_ Unimplemented) GetShift(w http.ResponseWriter, r *http.Request, shiftID int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Patch shift
// (PATCH /shift/{shiftID})
func (_ Unimplemented) PatchShift(w http.ResponseWriter, r *http.Request, shiftID int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get all vacations
// (GET /vacation)
func (_ Unimplemented) GetVacations(w http.ResponseWriter, r *http.Request, params GetVacationsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create vacation
// (POST /vacation)
func (_ Unimplemented) CreateVacation(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete vacation
// (DELETE /vacation/{vacationID})
func (_ Unimplemented) DeleteVacation(w http.ResponseWriter, r *http.Request, vacationID int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get vacation
// (GET /vacation/{vacationID})
func (_ Unimplemented) GetVacation(w http.ResponseWriter, r *http.Request, vacationID int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Patch vacation
// (PATCH /vacation/{vacationID})
func (_ Unimplemented) PatchVacation(w http.ResponseWriter, r *http.Request, vacationID int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetEmployees operation middleware
func (siw *ServerInterfaceWrapper) GetEmployees(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetEmployeesParams

	// ------------- Optional query parameter "filter" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "filter", r.URL.Query(), &params.Filter, runtime.BindQueryParameterOptions{Type: "object", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "filter", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEmployees(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateEmployee operation middleware
func (siw *ServerInterfaceWrapper) CreateEmployee(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateEmployee(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteEmployee operation middleware
func (siw *ServerInterfaceWrapper) DeleteEmployee(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "employeeID" -------------
	var employeeID int64

	err = runtime.BindStyledParameterWithOptions("simple", "employeeID", chi.URLParam(r, "employeeID"), &employeeID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "employeeID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteEmployee(w, r, employeeID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEmployee operation middleware
func (siw *ServerInterfaceWrapper) GetEmployee(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "employeeID" -------------
	var employeeID int64

	err = runtime.BindStyledParameterWithOptions("simple", "employeeID", chi.URLParam(r, "employeeID"), &employeeID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "employeeID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEmployee(w, r, employeeID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchEmployee operation middleware
func (siw *ServerInterfaceWrapper) PatchEmployee(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "employeeID" -------------
	var employeeID int64

	err = runtime.BindStyledParameterWithOptions("simple", "employeeID", chi.URLParam(r, "employeeID"), &employeeID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "employeeID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchEmployee(w, r, employeeID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetShifts operation middleware
func (siw *ServerInterfaceWrapper) GetShifts(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetShiftsParams

	// ------------- Optional query parameter "filter" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "filter", r.URL.Query(), &params.Filter, runtime.BindQueryParameterOptions{Type: "object", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "filter", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetShifts(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateShift operation middleware
func (siw *ServerInterfaceWrapper) CreateShift(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateShift(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetShiftTypes operation middleware
func (siw *ServerInterfaceWrapper) GetShiftTypes(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetShiftTypes(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateShiftType operation middleware
func (siw *ServerInterfaceWrapper) CreateShiftType(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateShiftType(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteShiftType operation middleware
func (siw *ServerInterfaceWrapper) DeleteShiftType(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "shiftTypeID" -------------
	var shiftTypeID int

	err = runtime.BindStyledParameterWithOptions("simple", "shiftTypeID", chi.URLParam(r, "shiftTypeID"), &shiftTypeID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "shiftTypeID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteShiftType(w, r, shiftTypeID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetShiftType operation middleware
func (siw *ServerInterfaceWrapper) GetShiftType(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "shiftTypeID" -------------
	var shiftTypeID int

	err = runtime.BindStyledParameterWithOptions("simple", "shiftTypeID", chi.URLParam(r, "shiftTypeID"), &shiftTypeID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "shiftTypeID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetShiftType(w, r, shiftTypeID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchShiftType operation middleware
func (siw *ServerInterfaceWrapper) PatchShiftType(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "shiftTypeID" -------------
	var shiftTypeID int

	err = runtime.BindStyledParameterWithOptions("simple", "shiftTypeID", chi.URLParam(r, "shiftTypeID"), &shiftTypeID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "shiftTypeID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchShiftType(w, r, shiftTypeID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteShift operation middleware
func (siw *ServerInterfaceWrapper) DeleteShift(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "shiftID" -------------
	var shiftID int

	err = runtime.BindStyledParameterWithOptions("simple", "shiftID", chi.URLParam(r, "shiftID"), &shiftID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "shiftID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteShift(w, r, shiftID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetShift operation middleware
func (siw *ServerInterfaceWrapper) GetShift(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "shiftID" -------------
	var shiftID int

	err = runtime.BindStyledParameterWithOptions("simple", "shiftID", chi.URLParam(r, "shiftID"), &shiftID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "shiftID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetShift(w, r, shiftID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchShift operation middleware
func (siw *ServerInterfaceWrapper) PatchShift(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "shiftID" -------------
	var shiftID int

	err = runtime.BindStyledParameterWithOptions("simple", "shiftID", chi.URLParam(r, "shiftID"), &shiftID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "shiftID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchShift(w, r, shiftID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVacations operation middleware
func (siw *ServerInterfaceWrapper) GetVacations(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetVacationsParams

	// ------------- Optional query parameter "filter" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "filter", r.URL.Query(), &params.Filter, runtime.BindQueryParameterOptions{Type: "object", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "filter", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVacations(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateVacation operation middleware
func (siw *ServerInterfaceWrapper) CreateVacation(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateVacation(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteVacation operation middleware
func (siw *ServerInterfaceWrapper) DeleteVacation(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "vacationID" -------------
	var vacationID int

	err = runtime.BindStyledParameterWithOptions("simple", "vacationID", chi.URLParam(r, "vacationID"), &vacationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "vacationID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteVacation(w, r, vacationID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVacation operation middleware
func (siw *ServerInterfaceWrapper) GetVacation(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "vacationID" -------------
	var vacationID int

	err = runtime.BindStyledParameterWithOptions("simple", "vacationID", chi.URLParam(r, "vacationID"), &vacationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "vacationID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVacation(w, r, vacationID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchVacation operation middleware
func (siw *ServerInterfaceWrapper) PatchVacation(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "vacationID" -------------
	var vacationID int

	err = runtime.BindStyledParameterWithOptions("simple", "vacationID", chi.URLParam(r, "vacationID"), &vacationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "vacationID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchVacation(w, r, vacationID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/employee", wrapper.GetEmployees)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/employee", wrapper.CreateEmployee)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/employee/{employeeID}", wrapper.DeleteEmployee)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/employee/{employeeID}", wrapper.GetEmployee)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/employee/{employeeID}", wrapper.PatchEmployee)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/shift", wrapper.GetShifts)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/shift", wrapper.CreateShift)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/shift-type", wrapper.GetShiftTypes)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/shift-type", wrapper.CreateShiftType)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/shift-type/{shiftTypeID}", wrapper.DeleteShiftType)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/shift-type/{shiftTypeID}", wrapper.GetShiftType)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/shift-type/{shiftTypeID}", wrapper.PatchShiftType)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/shift/{shiftID}", wrapper.DeleteShift)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/shift/{shiftID}", wrapper.GetShift)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/shift/{shiftID}", wrapper.PatchShift)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/vacation", wrapper.GetVacations)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/vacation", wrapper.CreateVacation)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/vacation/{vacationID}", wrapper.DeleteVacation)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/vacation/{vacationID}", wrapper.GetVacation)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/vacation/{vacationID}", wrapper.PatchVacation)
	})

	return r
}

type BadRequestJSONResponse Error

type ConflictJSONResponse Error

type ForbiddenJSONResponse Error

type NotFoundJSONResponse Error

type UnauthorizedJSONResponse Error

type GetEmployeesRequestObject struct {
	Params GetEmployeesParams
}

type GetEmployeesResponseObject interface {
	VisitGetEmployeesResponse(w http.ResponseWriter) error
}

type GetEmployees200JSONResponse EmployeeList

func (response GetEmployees200JSONResponse) VisitGetEmployeesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetEmployees401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetEmployees401JSONResponse) VisitGetEmployeesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetEmployees403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetEmployees403JSONResponse) VisitGetEmployeesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type CreateEmployeeRequestObject struct {
	Body *CreateEmployeeJSONRequestBody
}

type CreateEmployeeResponseObject interface {
	VisitCreateEmployeeResponse(w http.ResponseWriter) error
}

type CreateEmployee201JSONResponse Employee

func (response CreateEmployee201JSONResponse) VisitCreateEmployeeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateEmployee400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateEmployee400JSONResponse) VisitCreateEmployeeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateEmployee401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateEmployee401JSONResponse) VisitCreateEmployeeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateEmployee403JSONResponse struct{ ForbiddenJSONResponse }

func (response CreateEmployee403JSONResponse) VisitCreateEmployeeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type DeleteEmployeeRequestObject struct {
	EmployeeID int64 `json:"employeeID"`
}

type DeleteEmployeeResponseObject interface {
	VisitDeleteEmployeeResponse(w http.ResponseWriter) error
}

type DeleteEmployee204Response struct {
}

func (response DeleteEmployee204Response) VisitDeleteEmployeeResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteEmployee401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeleteEmployee401JSONResponse) VisitDeleteEmployeeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteEmployee403JSONResponse struct{ ForbiddenJSONResponse }

func (response DeleteEmployee403JSONResponse) VisitDeleteEmployeeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type DeleteEmployee404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteEmployee404JSONResponse) VisitDeleteEmployeeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteEmployee409JSONResponse struct{ ConflictJSONResponse }

func (response DeleteEmployee409JSONResponse) VisitDeleteEmployeeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type GetEmployeeRequestObject struct {
	EmployeeID int64 `json:"employeeID"`
}

type GetEmployeeResponseObject interface {
	VisitGetEmployeeResponse(w http.ResponseWriter) error
}

type GetEmployee200JSONResponse Employee

func (response GetEmployee200JSONResponse) VisitGetEmployeeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetEmployee401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetEmployee401JSONResponse) VisitGetEmployeeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetEmployee403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetEmployee403JSONResponse) VisitGetEmployeeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetEmployee404JSONResponse struct{ NotFoundJSONResponse }

func (response GetEmployee404JSONResponse) VisitGetEmployeeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PatchEmployeeRequestObject struct {
	EmployeeID int64 `json:"employeeID"`
	Body       *PatchEmployeeJSONRequestBody
}

type PatchEmployeeResponseObject interface {
	VisitPatchEmployeeResponse(w http.ResponseWriter) error
}

type PatchEmployee200JSONResponse Employee

func (response PatchEmployee200JSONResponse) VisitPatchEmployeeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PatchEmployee400JSONResponse struct{ BadRequestJSONResponse }

func (response PatchEmployee400JSONResponse) VisitPatchEmployeeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PatchEmployee401JSONResponse struct{ UnauthorizedJSONResponse }

func (response PatchEmployee401JSONResponse) VisitPatchEmployeeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PatchEmployee403JSONResponse struct{ ForbiddenJSONResponse }

func (response PatchEmployee403JSONResponse) VisitPatchEmployeeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type PatchEmployee404JSONResponse struct{ NotFoundJSONResponse }

func (response PatchEmployee404JSONResponse) VisitPatchEmployeeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetShiftsRequestObject struct {
	Params GetShiftsParams
}

type GetShiftsResponseObject interface {
	VisitGetShiftsResponse(w http.ResponseWriter) error
}

type GetShifts200JSONResponse ShiftList

func (response GetShifts200JSONResponse) VisitGetShiftsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetShifts401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetShifts401JSONResponse) VisitGetShiftsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetShifts403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetShifts403JSONResponse) VisitGetShiftsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type CreateShiftRequestObject struct {
	Body *CreateShiftJSONRequestBody
}

type CreateShiftResponseObject interface {
	VisitCreateShiftResponse(w http.ResponseWriter) error
}

type CreateShift201JSONResponse Shift

func (response CreateShift201JSONResponse) VisitCreateShiftResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateShift400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateShift400JSONResponse) VisitCreateShiftResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateShift401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateShift401JSONResponse) VisitCreateShiftResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateShift403JSONResponse struct{ ForbiddenJSONResponse }

func (response CreateShift403JSONResponse) VisitCreateShiftResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetShiftTypesRequestObject struct {
}

type GetShiftTypesResponseObject interface {
	VisitGetShiftTypesResponse(w http.ResponseWriter) error
}

type GetShiftTypes200JSONResponse ShiftTypeList

func (response GetShiftTypes200JSONResponse) VisitGetShiftTypesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetShiftTypes401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetShiftTypes401JSONResponse) VisitGetShiftTypesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetShiftTypes403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetShiftTypes403JSONResponse) VisitGetShiftTypesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type CreateShiftTypeRequestObject struct {
	Body *CreateShiftTypeJSONRequestBody
}

type CreateShiftTypeResponseObject interface {
	VisitCreateShiftTypeResponse(w http.ResponseWriter) error
}

type CreateShiftType201JSONResponse ShiftType

func (response CreateShiftType201JSONResponse) VisitCreateShiftTypeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateShiftType400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateShiftType400JSONResponse) VisitCreateShiftTypeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateShiftType401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateShiftType401JSONResponse) VisitCreateShiftTypeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateShiftType403JSONResponse struct{ ForbiddenJSONResponse }

func (response CreateShiftType403JSONResponse) VisitCreateShiftTypeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type DeleteShiftTypeRequestObject struct {
	ShiftTypeID int `json:"shiftTypeID"`
}

type DeleteShiftTypeResponseObject interface {
	VisitDeleteShiftTypeResponse(w http.ResponseWriter) error
}

type DeleteShiftType204Response struct {
}

func (response DeleteShiftType204Response) VisitDeleteShiftTypeResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteShiftType401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeleteShiftType401JSONResponse) VisitDeleteShiftTypeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteShiftType403JSONResponse struct{ ForbiddenJSONResponse }

func (response DeleteShiftType403JSONResponse) VisitDeleteShiftTypeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type DeleteShiftType404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteShiftType404JSONResponse) VisitDeleteShiftTypeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteShiftType409JSONResponse struct{ ConflictJSONResponse }

func (response DeleteShiftType409JSONResponse) VisitDeleteShiftTypeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type GetShiftTypeRequestObject struct {
	ShiftTypeID int `json:"shiftTypeID"`
}

type GetShiftTypeResponseObject interface {
	VisitGetShiftTypeResponse(w http.ResponseWriter) error
}

type GetShiftType200JSONResponse ShiftType

func (response GetShiftType200JSONResponse) VisitGetShiftTypeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetShiftType401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetShiftType401JSONResponse) VisitGetShiftTypeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetShiftType403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetShiftType403JSONResponse) VisitGetShiftTypeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetShiftType404JSONResponse struct{ NotFoundJSONResponse }

func (response GetShiftType404JSONResponse) VisitGetShiftTypeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PatchShiftTypeRequestObject struct {
	ShiftTypeID int `json:"shiftTypeID"`
	Body        *PatchShiftTypeJSONRequestBody
}

type PatchShiftTypeResponseObject interface {
	VisitPatchShiftTypeResponse(w http.ResponseWriter) error
}

type PatchShiftType200JSONResponse ShiftType

func (response PatchShiftType200JSONResponse) VisitPatchShiftTypeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PatchShiftType400JSONResponse struct{ BadRequestJSONResponse }

func (response PatchShiftType400JSONResponse) VisitPatchShiftTypeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PatchShiftType401JSONResponse struct{ UnauthorizedJSONResponse }

func (response PatchShiftType401JSONResponse) VisitPatchShiftTypeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PatchShiftType403JSONResponse struct{ ForbiddenJSONResponse }

func (response PatchShiftType403JSONResponse) VisitPatchShiftTypeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type PatchShiftType404JSONResponse struct{ NotFoundJSONResponse }

func (response PatchShiftType404JSONResponse) VisitPatchShiftTypeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteShiftRequestObject struct {
	ShiftID int `json:"shiftID"`
}

type DeleteShiftResponseObject interface {
	VisitDeleteShiftResponse(w http.ResponseWriter) error
}

type DeleteShift204Response struct {
}

func (response DeleteShift204Response) VisitDeleteShiftResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteShift401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeleteShift401JSONResponse) VisitDeleteShiftResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteShift403JSONResponse struct{ ForbiddenJSONResponse }

func (response DeleteShift403JSONResponse) VisitDeleteShiftResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type DeleteShift404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteShift404JSONResponse) VisitDeleteShiftResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteShift409JSONResponse struct{ ConflictJSONResponse }

func (response DeleteShift409JSONResponse) VisitDeleteShiftResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type GetShiftRequestObject struct {
	ShiftID int `json:"shiftID"`
}

type GetShiftResponseObject interface {
	VisitGetShiftResponse(w http.ResponseWriter) error
}

type GetShift200JSONResponse Shift

func (response GetShift200JSONResponse) VisitGetShiftResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetShift401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetShift401JSONResponse) VisitGetShiftResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetShift403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetShift403JSONResponse) VisitGetShiftResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetShift404JSONResponse struct{ NotFoundJSONResponse }

func (response GetShift404JSONResponse) VisitGetShiftResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PatchShiftRequestObject struct {
	ShiftID int `json:"shiftID"`
	Body    *PatchShiftJSONRequestBody
}

type PatchShiftResponseObject interface {
	VisitPatchShiftResponse(w http.ResponseWriter) error
}

type PatchShift200JSONResponse Shift

func (response PatchShift200JSONResponse) VisitPatchShiftResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PatchShift400JSONResponse struct{ BadRequestJSONResponse }

func (response PatchShift400JSONResponse) VisitPatchShiftResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PatchShift401JSONResponse struct{ UnauthorizedJSONResponse }

func (response PatchShift401JSONResponse) VisitPatchShiftResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PatchShift403JSONResponse struct{ ForbiddenJSONResponse }

func (response PatchShift403JSONResponse) VisitPatchShiftResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type PatchShift404JSONResponse struct{ NotFoundJSONResponse }

func (response PatchShift404JSONResponse) VisitPatchShiftResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetVacationsRequestObject struct {
	Params GetVacationsParams
}

type GetVacationsResponseObject interface {
	VisitGetVacationsResponse(w http.ResponseWriter) error
}

type GetVacations200JSONResponse VacationList

func (response GetVacations200JSONResponse) VisitGetVacationsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetVacations401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetVacations401JSONResponse) VisitGetVacationsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetVacations403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetVacations403JSONResponse) VisitGetVacationsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type CreateVacationRequestObject struct {
	Body *CreateVacationJSONRequestBody
}

type CreateVacationResponseObject interface {
	VisitCreateVacationResponse(w http.ResponseWriter) error
}

type CreateVacation201JSONResponse Vacation

func (response CreateVacation201JSONResponse) VisitCreateVacationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateVacation400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateVacation400JSONResponse) VisitCreateVacationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateVacation401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateVacation401JSONResponse) VisitCreateVacationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateVacation403JSONResponse struct{ ForbiddenJSONResponse }

func (response CreateVacation403JSONResponse) VisitCreateVacationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type CreateVacation409JSONResponse struct{ ConflictJSONResponse }

func (response CreateVacation409JSONResponse) VisitCreateVacationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type DeleteVacationRequestObject struct {
	VacationID int `json:"vacationID"`
}

type DeleteVacationResponseObject interface {
	VisitDeleteVacationResponse(w http.ResponseWriter) error
}

type DeleteVacation204Response struct {
}

func (response DeleteVacation204Response) VisitDeleteVacationResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteVacation401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeleteVacation401JSONResponse) VisitDeleteVacationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteVacation403JSONResponse struct{ ForbiddenJSONResponse }

func (response DeleteVacation403JSONResponse) VisitDeleteVacationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type DeleteVacation404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteVacation404JSONResponse) VisitDeleteVacationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetVacationRequestObject struct {
	VacationID int `json:"vacationID"`
}

type GetVacationResponseObject interface {
	VisitGetVacationResponse(w http.ResponseWriter) error
}

type GetVacation200JSONResponse Vacation

func (response GetVacation200JSONResponse) VisitGetVacationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetVacation401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetVacation401JSONResponse) VisitGetVacationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetVacation403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetVacation403JSONResponse) VisitGetVacationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetVacation404JSONResponse struct{ NotFoundJSONResponse }

func (response GetVacation404JSONResponse) VisitGetVacationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PatchVacationRequestObject struct {
	VacationID int `json:"vacationID"`
	Body       *PatchVacationJSONRequestBody
}

type PatchVacationResponseObject interface {
	VisitPatchVacationResponse(w http.ResponseWriter) error
}

type PatchVacation200JSONResponse Vacation

func (response PatchVacation200JSONResponse) VisitPatchVacationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PatchVacation400JSONResponse struct{ BadRequestJSONResponse }

func (response PatchVacation400JSONResponse) VisitPatchVacationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PatchVacation401JSONResponse struct{ UnauthorizedJSONResponse }

func (response PatchVacation401JSONResponse) VisitPatchVacationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PatchVacation403JSONResponse struct{ ForbiddenJSONResponse }

func (response PatchVacation403JSONResponse) VisitPatchVacationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type PatchVacation404JSONResponse struct{ NotFoundJSONResponse }

func (response PatchVacation404JSONResponse) VisitPatchVacationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PatchVacation409JSONResponse struct{ ConflictJSONResponse }

func (response PatchVacation409JSONResponse) VisitPatchVacationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Get all employees
	// (GET /employee)
	GetEmployees(ctx context.Context, request GetEmployeesRequestObject) (GetEmployeesResponseObject, error)
	// Create employee
	// (POST /employee)
	CreateEmployee(ctx context.Context, request CreateEmployeeRequestObject) (CreateEmployeeResponseObject, error)
	// Delete employee
	// (DELETE /employee/{employeeID})
	DeleteEmployee(ctx context.Context, request DeleteEmployeeRequestObject) (DeleteEmployeeResponseObject, error)
	// Get employee
	// (GET /employee/{employeeID})
	GetEmployee(ctx context.Context, request GetEmployeeRequestObject) (GetEmployeeResponseObject, error)
	// Patch employee
	// (PATCH /employee/{employeeID})
	PatchEmployee(ctx context.Context, request PatchEmployeeRequestObject) (PatchEmployeeResponseObject, error)
	// Get all shifts
	// (GET /shift)
	GetShifts(ctx context.Context, request GetShiftsRequestObject) (GetShiftsResponseObject, error)
	// Create shift
	// (POST /shift)
	CreateShift(ctx context.Context, request CreateShiftRequestObject) (CreateShiftResponseObject, error)
	// Get all shift types
	// (GET /shift-type)
	GetShiftTypes(ctx context.Context, request GetShiftTypesRequestObject) (GetShiftTypesResponseObject, error)
	// Create shift type
	// (POST /shift-type)
	CreateShiftType(ctx context.Context, request CreateShiftTypeRequestObject) (CreateShiftTypeResponseObject, error)
	// Delete shift type
	// (DELETE /shift-type/{shiftTypeID})
	DeleteShiftType(ctx context.Context, request DeleteShiftTypeRequestObject) (DeleteShiftTypeResponseObject, error)
	// Get shift type
	// (GET /shift-type/{shiftTypeID})
	GetShiftType(ctx context.Context, request GetShiftTypeRequestObject) (GetShiftTypeResponseObject, error)
	// Patch shift type
	// (PATCH /shift-type/{shiftTypeID})
	PatchShiftType(ctx context.Context, request PatchShiftTypeRequestObject) (PatchShiftTypeResponseObject, error)
	// Delete shift
	// (DELETE /shift/{shiftID})
	DeleteShift(ctx context.Context, request DeleteShiftRequestObject) (DeleteShiftResponseObject, error)
	// Get shift
	// (GET /shift/{shiftID})
	GetShift(ctx context.Context, request GetShiftRequestObject) (GetShiftResponseObject, error)
	// Patch shift
	// (PATCH /shift/{shiftID})
	PatchShift(ctx context.Context, request PatchShiftRequestObject) (PatchShiftResponseObject, error)
	// Get all vacations
	// (GET /vacation)
	GetVacations(ctx context.Context, request GetVacationsRequestObject) (GetVacationsResponseObject, error)
	// Create vacation
	// (POST /vacation)
	CreateVacation(ctx context.Context, request CreateVacationRequestObject) (CreateVacationResponseObject, error)
	// Delete vacation
	// (DELETE /vacation/{vacationID})
	DeleteVacation(ctx context.Context, request DeleteVacationRequestObject) (DeleteVacationResponseObject, error)
	// Get vacation
	// (GET /vacation/{vacationID})
	GetVacation(ctx context.Context, request GetVacationRequestObject) (GetVacationResponseObject, error)
	// Patch vacation
	// (PATCH /vacation/{vacationID})
	PatchVacation(ctx context.Context, request PatchVacationRequestObject) (PatchVacationResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetEmployees operation middleware
func (sh *strictHandler) GetEmployees(w http.ResponseWriter, r *http.Request, params GetEmployeesParams) {
	var request GetEmployeesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetEmployees(ctx, request.(GetEmployeesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetEmployees")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetEmployeesResponseObject); ok {
		if err := validResponse.VisitGetEmployeesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateEmployee operation middleware
func (sh *strictHandler) CreateEmployee(w http.ResponseWriter, r *http.Request) {
	var request CreateEmployeeRequestObject

	var body CreateEmployeeJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateEmployee(ctx, request.(CreateEmployeeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateEmployee")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateEmployeeResponseObject); ok {
		if err := validResponse.VisitCreateEmployeeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteEmployee operation middleware
func (sh *strictHandler) DeleteEmployee(w http.ResponseWriter, r *http.Request, employeeID int64) {
	var request DeleteEmployeeRequestObject

	request.EmployeeID = employeeID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteEmployee(ctx, request.(DeleteEmployeeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteEmployee")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteEmployeeResponseObject); ok {
		if err := validResponse.VisitDeleteEmployeeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetEmployee operation middleware
func (sh *strictHandler) GetEmployee(w http.ResponseWriter, r *http.Request, employeeID int64) {
	var request GetEmployeeRequestObject

	request.EmployeeID = employeeID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetEmployee(ctx, request.(GetEmployeeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetEmployee")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetEmployeeResponseObject); ok {
		if err := validResponse.VisitGetEmployeeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PatchEmployee operation middleware
func (sh *strictHandler) PatchEmployee(w http.ResponseWriter, r *http.Request, employeeID int64) {
	var request PatchEmployeeRequestObject

	request.EmployeeID = employeeID

	var body PatchEmployeeJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PatchEmployee(ctx, request.(PatchEmployeeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PatchEmployee")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PatchEmployeeResponseObject); ok {
		if err := validResponse.VisitPatchEmployeeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetShifts operation middleware
func (sh *strictHandler) GetShifts(w http.ResponseWriter, r *http.Request, params GetShiftsParams) {
	var request GetShiftsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetShifts(ctx, request.(GetShiftsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetShifts")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetShiftsResponseObject); ok {
		if err := validResponse.VisitGetShiftsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateShift operation middleware
func (sh *strictHandler) CreateShift(w http.ResponseWriter, r *http.Request) {
	var request CreateShiftRequestObject

	var body CreateShiftJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateShift(ctx, request.(CreateShiftRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateShift")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateShiftResponseObject); ok {
		if err := validResponse.VisitCreateShiftResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetShiftTypes operation middleware
func (sh *strictHandler) GetShiftTypes(w http.ResponseWriter, r *http.Request) {
	var request GetShiftTypesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetShiftTypes(ctx, request.(GetShiftTypesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetShiftTypes")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetShiftTypesResponseObject); ok {
		if err := validResponse.VisitGetShiftTypesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateShiftType operation middleware
func (sh *strictHandler) CreateShiftType(w http.ResponseWriter, r *http.Request) {
	var request CreateShiftTypeRequestObject

	var body CreateShiftTypeJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateShiftType(ctx, request.(CreateShiftTypeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateShiftType")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateShiftTypeResponseObject); ok {
		if err := validResponse.VisitCreateShiftTypeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteShiftType operation middleware
func (sh *strictHandler) DeleteShiftType(w http.ResponseWriter, r *http.Request, shiftTypeID int) {
	var request DeleteShiftTypeRequestObject

	request.ShiftTypeID = shiftTypeID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteShiftType(ctx, request.(DeleteShiftTypeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteShiftType")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteShiftTypeResponseObject); ok {
		if err := validResponse.VisitDeleteShiftTypeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetShiftType operation middleware
func (sh *strictHandler) GetShiftType(w http.ResponseWriter, r *http.Request, shiftTypeID int) {
	var request GetShiftTypeRequestObject

	request.ShiftTypeID = shiftTypeID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetShiftType(ctx, request.(GetShiftTypeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetShiftType")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetShiftTypeResponseObject); ok {
		if err := validResponse.VisitGetShiftTypeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PatchShiftType operation middleware
func (sh *strictHandler) PatchShiftType(w http.ResponseWriter, r *http.Request, shiftTypeID int) {
	var request PatchShiftTypeRequestObject

	request.ShiftTypeID = shiftTypeID

	var body PatchShiftTypeJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PatchShiftType(ctx, request.(PatchShiftTypeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PatchShiftType")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PatchShiftTypeResponseObject); ok {
		if err := validResponse.VisitPatchShiftTypeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteShift operation middleware
func (sh *strictHandler) DeleteShift(w http.ResponseWriter, r *http.Request, shiftID int) {
	var request DeleteShiftRequestObject

	request.ShiftID = shiftID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteShift(ctx, request.(DeleteShiftRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteShift")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteShiftResponseObject); ok {
		if err := validResponse.VisitDeleteShiftResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetShift operation middleware
func (sh *strictHandler) GetShift(w http.ResponseWriter, r *http.Request, shiftID int) {
	var request GetShiftRequestObject

	request.ShiftID = shiftID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetShift(ctx, request.(GetShiftRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetShift")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetShiftResponseObject); ok {
		if err := validResponse.VisitGetShiftResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PatchShift operation middleware
func (sh *strictHandler) PatchShift(w http.ResponseWriter, r *http.Request, shiftID int) {
	var request PatchShiftRequestObject

	request.ShiftID = shiftID

	var body PatchShiftJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PatchShift(ctx, request.(PatchShiftRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PatchShift")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PatchShiftResponseObject); ok {
		if err := validResponse.VisitPatchShiftResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetVacations operation middleware
func (sh *strictHandler) GetVacations(w http.ResponseWriter, r *http.Request, params GetVacationsParams) {
	var request GetVacationsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetVacations(ctx, request.(GetVacationsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetVacations")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetVacationsResponseObject); ok {
		if err := validResponse.VisitGetVacationsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateVacation operation middleware
func (sh *strictHandler) CreateVacation(w http.ResponseWriter, r *http.Request) {
	var request CreateVacationRequestObject

	var body CreateVacationJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateVacation(ctx, request.(CreateVacationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateVacation")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateVacationResponseObject); ok {
		if err := validResponse.VisitCreateVacationResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteVacation operation middleware
func (sh *strictHandler) DeleteVacation(w http.ResponseWriter, r *http.Request, vacationID int) {
	var request DeleteVacationRequestObject

	request.VacationID = vacationID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteVacation(ctx, request.(DeleteVacationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteVacation")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteVacationResponseObject); ok {
		if err := validResponse.VisitDeleteVacationResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetVacation operation middleware
func (sh *strictHandler) GetVacation(w http.ResponseWriter, r *http.Request, vacationID int) {
	var request GetVacationRequestObject

	request.VacationID = vacationID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetVacation(ctx, request.(GetVacationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetVacation")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetVacationResponseObject); ok {
		if err := validResponse.VisitGetVacationResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PatchVacation operation middleware
func (sh *strictHandler) PatchVacation(w http.ResponseWriter, r *http.Request, vacationID int) {
	var request PatchVacationRequestObject

	request.VacationID = vacationID

	var body PatchVacationJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PatchVacation(ctx, request.(PatchVacationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PatchVacation")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PatchVacationResponseObject); ok {
		if err := validResponse.VisitPatchVacationResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xbW0/sOBL+K5F3H3NOBw5a7fTbnAFGSDOAFlhpdwa1TFJpPErsjO1mh0X57yvbuThX",
	"pw+dbhj2rUl8KddXl89V4QWFLM0YBSoFWr4gDiJjVID+4yuO/gG/b0BI9VfIqASqf+IsS0iIJWF08Ztg",
	"VD0T4SOkWP36K4cYLdFfFvXSC/NWLM44Zxzlee6jCETISaYWQUukX3iEetzs6GWY41QsHlj0jHIf/cBo",
	"nJBwD5KUO/2Klr8i7+rhNwil94iFxyHBEiIvwhIrkc4ZfyBRBHR+mS6o2MQxCQlQ6WWcPJEE1iCUFJdM",
	"nrMNjeYXolAFZdKL9Y65j+4o3shHxsl/YQ8SNHZTr4sZasFTyDCXKVB588i4loBukgQ/JICWkm/ARxln",
	"GXBJjHUTLbB8zgAtEaES1sDVkShOwXojJCd0rXdTpkm4OugvanYx9N4vhzKtILXGWZol7Bn0OjhJrmK0",
	"/OWltX/IQZnTCmtZ4Q+cZkpUdBwcn3wKvnw6Dm6D75ZHx8vjv/8b+ShmPFVDUYQlfJIkBeS3ZVT6KrXg",
	"UnJbX7lfaKTaiFD5t5N6E0tFGRPEQDK+x3UxrtphI4C7Jt0J4MWErs57lO2wpQKJr1gAyu8tbPSTZRsV",
	"HEryZOP/wFgCmCrpY8KFXA3Yh49SEkUJVO/b1tcZLyBkNFpNszdr7+bMMfP7QZtY0winK8tv66Y2rpUx",
	"lYEj9ljK5AnKQlYDhuianXdUYeN9ThJprG8I8YH1LQv4Bg00jcZpFAlJiZy2MotjARPHtmzNIUY+YlM/",
	"EUMHWsFUQtr8McXOUL0R5hzrRC+ZxEkjIh4FwRSsaxGvsQwft3PtVwPrigad91t7xni42LXn1Nqs0ulO",
	"YsjEHDMl8vdGPk0dOtCHLIJmlj37+fqnq3+dna0ur25X51d3l6d96TQFIfC6PbU4ocWEfEf0LtfxjSR9",
	"kjdz5UHZy80jieXeqQtYnGmKgbVoS4/DqGOszPPxJfWBb9VA5UdZtOvD7YDHaBFrElP/2bH1qEj5DcH6",
	"FC4klhvRPGSWYEoh0hIkINUvTENIEnAbud5n0J625SLWgTtBpDSV1WTGWtvCqt9c8r7wYp/O3tMvddpc",
	"dvDsQ9RDrbKKOUv78HJSBT1bsm+a29KgO/vMxUvauEyYUpntN7AYDccuKIyJkbvlL3rNAfIy5NW7R/og",
	"kNwWUfq1SW549Tr+NPeYljDHc6Vaf2dGVeahXRuWWnfAuLbQZ307d1IUSDFJeqnqEK6cJS2uhaOU0EWK",
	"KV4DX1QUwZ/Cb8z+xap92P0Tm/LUn4Dq9KVyoBGh6wXOMs6eIFpwUAfvS+R7Ij2VnFuznxKpmgA1nvTw",
	"/bSsgbkDJI1W23AmLqcOz0dsbls61NSAixF1gsI4m7FOZeljzGX+z2hmyYWleneRTKrotttcUi47kEp2",
	"5Xnu6umoJ06Z/pqI2dWMekRozEyh1O5afH994d1kEJK4aId4MePezd2Pp+TK+/76Qq1OpJag8fAJuDAr",
	"BJ+Dz0faEDOgOCNoib58Dj5/QT7KsHzUx1jYSWVtrFUBo3e8iNAS/QiyTChCz+Q4BQlc6ODTaseVA73Y",
	"eLqP4I8s0WUUo1Gihv2+Af5clhKWqBo7sc/TrMwWQcpqQB4Hwe6aSnb9sqe3dLMJQxC6pXYSHA2tVom3",
	"aPai1KQv7kl1y1B3rzZpivmzgcbDSeKBhY/Ea2GHanRvqoY9yJpkclazo6KJ+pVFzztXYJG5elR4Cf+p",
	"TmC6pHbSUWaTdwA+2rl8vd3lUqqCzhnAAjdgVgv8IIZhlO3ZxLdrFrlfe//ipfx1cZqbWJSAiZFNmznV",
	"zy2bacUD7d8qutTuXa/cAdZ2+U45JiWUpJsULY96UkzX50+6IbTCz5wm2hsYasaJe0bVhNcTvnNPqD5n",
	"aMJtQHHA7TvD+1tCM9iLg+87em9tF51w78I4K/lVE2VNu94IzvPlGEMuxwJ5TCCJPMk8oyd3ogn2m2iK",
	"C/VbTjSvs2EN0YTEJMpm0lDQ0sUpJyE1o+Zko3alft5AVheh3yoPFSUmJagGRRcDNUXxeUKD3UQa4J5a",
	"yP0Tz6IV0AOlluedUk5RYNm2gMqnP5Wd1VHHvn3O9G1mXmeqCvBv2qE8WSijoVPToZ7kWro1MKN7WX2S",
	"URdTEh/Iz0x3ZMjXtGDv2eH0CYYspOl6ixdRKmTSVc+2IDdrtNYepY2vv9tZyH2M250baN8dUw8JYrAn",
	"l353d7opyI7d6w6F7ozpZPAmZ7m9vsuJw1zmpiaVD3Kf2yIJFflneu6ZbtR7yjkfKN30XuVGk8yh0Ar2",
	"cC97n4ml/zruSid7xHGmNOJIIQfPHsOifaSkMVAqeLK+sRqKN+UnBc4iYDVwzjpg6xOXeWNU44OPt1q8",
	"eLLwKTGucHUVLqrPUOaJEK3vqQbKFqW0+y9a1F/hdCUr372HisXrqEhR4niqbaHHjuxwsXgpf03il5aR",
	"uZNdvfLMLLPC980TzT7eOA6W74zmB8Qi2Iv7vj8a6YJ0jEweBtb5EsYgq6y89pDEclLa+DPSy9flGcNH",
	"HWkmrx63A/bP+v8MGl/htT6i0J9e906ySVLLC4YnVX1W+x7mGF51kew5pjqT3+f/CwAA//8tFgv/0UUA",
	"AA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
