// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// DepartmentShort defines model for DepartmentShort.
type DepartmentShort struct {
	Id   int    `json:"id"`
	Name string `json:"name"`
}

// Employee defines model for Employee.
type Employee struct {
	Active     *bool            `json:"active,omitempty"`
	CreatedAt  *time.Time       `json:"created_at,omitempty"`
	Department *DepartmentShort `json:"department,omitempty"`
	FirstName  string           `json:"first_name"`
	Id         int64            `json:"id"`
	MiddleName *string          `json:"middle_name,omitempty"`
	Position   *PositionShort   `json:"position,omitempty"`
	SecondName string           `json:"second_name"`
	User       *UserShort       `json:"user,omitempty"`
}

// EmployeeBase defines model for EmployeeBase.
type EmployeeBase struct {
	Active     *bool   `json:"active,omitempty"`
	FirstName  string  `json:"first_name"`
	MiddleName *string `json:"middle_name,omitempty"`
	SecondName string  `json:"second_name"`
}

// EmployeeCreate defines model for EmployeeCreate.
type EmployeeCreate struct {
	Active       *bool   `json:"active,omitempty"`
	DepartmentId *int    `json:"department_id,omitempty"`
	FirstName    string  `json:"first_name"`
	MiddleName   *string `json:"middle_name,omitempty"`
	PositionId   *int    `json:"position_id,omitempty"`
	SecondName   string  `json:"second_name"`
	UserId       *int64  `json:"user_id,omitempty"`
}

// EmployeeFilter defines model for EmployeeFilter.
type EmployeeFilter struct {
	Active       *bool   `json:"active,omitempty"`
	DepartmentId *int    `json:"department_id,omitempty"`
	FirstName    *string `json:"first_name,omitempty"`
	Limit        *int    `json:"limit,omitempty"`
	Offset       *int    `json:"offset,omitempty"`
	SecondName   *string `json:"second_name,omitempty"`
}

// EmployeeList defines model for EmployeeList.
type EmployeeList struct {
	Items *[]Employee `json:"items,omitempty"`
	Total *int        `json:"total,omitempty"`
}

// EmployeePatch defines model for EmployeePatch.
type EmployeePatch struct {
	Active       *bool   `json:"active,omitempty"`
	DepartmentId *int    `json:"department_id,omitempty"`
	FirstName    *string `json:"first_name,omitempty"`
	MiddleName   *string `json:"middle_name,omitempty"`
	PositionId   *int    `json:"position_id,omitempty"`
	SecondName   *string `json:"second_name,omitempty"`
	UserId       *int64  `json:"user_id,omitempty"`
}

// EmployeeShort defines model for EmployeeShort.
type EmployeeShort struct {
	Active     *bool   `json:"active,omitempty"`
	FirstName  string  `json:"first_name"`
	Id         int64   `json:"id"`
	MiddleName *string `json:"middle_name,omitempty"`
	SecondName string  `json:"second_name"`
}

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// PositionShort defines model for PositionShort.
type PositionShort struct {
	Id   int    `json:"id"`
	Name string `json:"name"`
}

// Shift defines model for Shift.
type Shift struct {
	CreatedAt *time.Time         `json:"created_at,omitempty"`
	Date      openapi_types.Date `json:"date"`
	Employee  *EmployeeShort     `json:"employee,omitempty"`
	Id        int                `json:"id"`
	ShiftType *ShiftType         `json:"shift_type,omitempty"`
	Status    *string            `json:"status,omitempty"`
	UpdatedAt *time.Time         `json:"updated_at,omitempty"`
}

// ShiftBase defines model for ShiftBase.
type ShiftBase struct {
	Date   openapi_types.Date `json:"date"`
	Status *string            `json:"status,omitempty"`
}

// ShiftCreate defines model for ShiftCreate.
type ShiftCreate struct {
	Date        openapi_types.Date `json:"date"`
	EmployeeId  *int64             `json:"employee_id,omitempty"`
	ShiftTypeId *int               `json:"shift_type_id,omitempty"`
	Status      *string            `json:"status,omitempty"`
}

// ShiftFilter defines model for ShiftFilter.
type ShiftFilter struct {
	DateFrom    *openapi_types.Date `json:"date_from,omitempty"`
	DateTo      *openapi_types.Date `json:"date_to,omitempty"`
	EmployeeId  *int                `json:"employee_id,omitempty"`
	Limit       *int                `json:"limit,omitempty"`
	Offset      *int                `json:"offset,omitempty"`
	ShiftTypeId *int                `json:"shift_type_id,omitempty"`
	Status      *string             `json:"status,omitempty"`
}

// ShiftList defines model for ShiftList.
type ShiftList struct {
	Items *[]Shift `json:"items,omitempty"`
	Total *int     `json:"total,omitempty"`
}

// ShiftPatch defines model for ShiftPatch.
type ShiftPatch struct {
	Date        *openapi_types.Date `json:"date,omitempty"`
	EmployeeId  *int                `json:"employee_id,omitempty"`
	ShiftTypeId *int                `json:"shift_type_id,omitempty"`
	Status      *string             `json:"status,omitempty"`
}

// ShiftType defines model for ShiftType.
type ShiftType struct {
	Id   *int    `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

// ShiftTypeCreate defines model for ShiftTypeCreate.
type ShiftTypeCreate struct {
	Name string `json:"name"`
}

// ShiftTypeList defines model for ShiftTypeList.
type ShiftTypeList struct {
	Items *[]ShiftType `json:"items,omitempty"`
	Total *int         `json:"total,omitempty"`
}

// ShiftTypePatch defines model for ShiftTypePatch.
type ShiftTypePatch struct {
	Name *string `json:"name,omitempty"`
}

// UserShort defines model for UserShort.
type UserShort struct {
	Email string `json:"email"`
	Id    int    `json:"id"`
	Role  string `json:"role"`
}

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// GetEmployeesParams defines parameters for GetEmployees.
type GetEmployeesParams struct {
	// Filter Employees filter
	Filter *EmployeeFilter `form:"filter,omitempty" json:"filter,omitempty"`
}

// GetShiftsParams defines parameters for GetShifts.
type GetShiftsParams struct {
	// Filter Shifts filter
	Filter *ShiftFilter `form:"filter,omitempty" json:"filter,omitempty"`
}

// CreateEmployeeJSONRequestBody defines body for CreateEmployee for application/json ContentType.
type CreateEmployeeJSONRequestBody = EmployeeCreate

// PatchEmployeeJSONRequestBody defines body for PatchEmployee for application/json ContentType.
type PatchEmployeeJSONRequestBody = EmployeePatch

// CreateShiftJSONRequestBody defines body for CreateShift for application/json ContentType.
type CreateShiftJSONRequestBody = ShiftCreate

// CreateShiftTypeJSONRequestBody defines body for CreateShiftType for application/json ContentType.
type CreateShiftTypeJSONRequestBody = ShiftTypeCreate

// PatchShiftTypeJSONRequestBody defines body for PatchShiftType for application/json ContentType.
type PatchShiftTypeJSONRequestBody = ShiftTypePatch

// PatchShiftJSONRequestBody defines body for PatchShift for application/json ContentType.
type PatchShiftJSONRequestBody = ShiftPatch

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get all employees
	// (GET /employee)
	GetEmployees(w http.ResponseWriter, r *http.Request, params GetEmployeesParams)
	// Create employee
	// (POST /employee)
	CreateEmployee(w http.ResponseWriter, r *http.Request)
	// Delete employee
	// (DELETE /employee/{employeeID})
	DeleteEmployee(w http.ResponseWriter, r *http.Request, employeeID int64)
	// Get employee
	// (GET /employee/{employeeID})
	GetEmployee(w http.ResponseWriter, r *http.Request, employeeID int64)
	// Patch employee
	// (PATCH /employee/{employeeID})
	PatchEmployee(w http.ResponseWriter, r *http.Request, employeeID int64)
	// Get all shifts
	// (GET /shift)
	GetShifts(w http.ResponseWriter, r *http.Request, params GetShiftsParams)
	// Create shift
	// (POST /shift)
	CreateShift(w http.ResponseWriter, r *http.Request)
	// Get all shift types
	// (GET /shift-type)
	GetShiftTypes(w http.ResponseWriter, r *http.Request)
	// Create shift type
	// (POST /shift-type)
	CreateShiftType(w http.ResponseWriter, r *http.Request)
	// Delete shift type
	// (DELETE /shift-type/{shiftTypeID})
	DeleteShiftType(w http.ResponseWriter, r *http.Request, shiftTypeID int)
	// Get shift type
	// (GET /shift-type/{shiftTypeID})
	GetShiftType(w http.ResponseWriter, r *http.Request, shiftTypeID int)
	// Patch shift type
	// (PATCH /shift-type/{shiftTypeID})
	PatchShiftType(w http.ResponseWriter, r *http.Request, shiftTypeID int)
	// Delete shift
	// (DELETE /shift/{shiftID})
	DeleteShift(w http.ResponseWriter, r *http.Request, shiftID int)
	// Get shift
	// (GET /shift/{shiftID})
	GetShift(w http.ResponseWriter, r *http.Request, shiftID int)
	// Patch shift
	// (PATCH /shift/{shiftID})
	PatchShift(w http.ResponseWriter, r *http.Request, shiftID int)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Get all employees
// (GET /employee)
func (_ Unimplemented) GetEmployees(w http.ResponseWriter, r *http.Request, params GetEmployeesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create employee
// (POST /employee)
func (_ Unimplemented) CreateEmployee(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete employee
// (DELETE /employee/{employeeID})
func (_ Unimplemented) DeleteEmployee(w http.ResponseWriter, r *http.Request, employeeID int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get employee
// (GET /employee/{employeeID})
func (_ Unimplemented) GetEmployee(w http.ResponseWriter, r *http.Request, employeeID int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Patch employee
// (PATCH /employee/{employeeID})
func (_ Unimplemented) PatchEmployee(w http.ResponseWriter, r *http.Request, employeeID int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get all shifts
// (GET /shift)
func (_ Unimplemented) GetShifts(w http.ResponseWriter, r *http.Request, params GetShiftsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create shift
// (POST /shift)
func (_ Unimplemented) CreateShift(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get all shift types
// (GET /shift-type)
func (_ Unimplemented) GetShiftTypes(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create shift type
// (POST /shift-type)
func (_ Unimplemented) CreateShiftType(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete shift type
// (DELETE /shift-type/{shiftTypeID})
func (_ Unimplemented) DeleteShiftType(w http.ResponseWriter, r *http.Request, shiftTypeID int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get shift type
// (GET /shift-type/{shiftTypeID})
func (_ Unimplemented) GetShiftType(w http.ResponseWriter, r *http.Request, shiftTypeID int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Patch shift type
// (PATCH /shift-type/{shiftTypeID})
func (_ Unimplemented) PatchShiftType(w http.ResponseWriter, r *http.Request, shiftTypeID int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete shift
// (DELETE /shift/{shiftID})
func (_ Unimplemented) DeleteShift(w http.ResponseWriter, r *http.Request, shiftID int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get shift
// (GET /shift/{shiftID})
func (_ Unimplemented) GetShift(w http.ResponseWriter, r *http.Request, shiftID int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Patch shift
// (PATCH /shift/{shiftID})
func (_ Unimplemented) PatchShift(w http.ResponseWriter, r *http.Request, shiftID int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetEmployees operation middleware
func (siw *ServerInterfaceWrapper) GetEmployees(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetEmployeesParams

	// ------------- Optional query parameter "filter" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "filter", r.URL.Query(), &params.Filter, runtime.BindQueryParameterOptions{Type: "object", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "filter", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEmployees(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateEmployee operation middleware
func (siw *ServerInterfaceWrapper) CreateEmployee(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateEmployee(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteEmployee operation middleware
func (siw *ServerInterfaceWrapper) DeleteEmployee(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "employeeID" -------------
	var employeeID int64

	err = runtime.BindStyledParameterWithOptions("simple", "employeeID", chi.URLParam(r, "employeeID"), &employeeID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "employeeID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteEmployee(w, r, employeeID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEmployee operation middleware
func (siw *ServerInterfaceWrapper) GetEmployee(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "employeeID" -------------
	var employeeID int64

	err = runtime.BindStyledParameterWithOptions("simple", "employeeID", chi.URLParam(r, "employeeID"), &employeeID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "employeeID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEmployee(w, r, employeeID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchEmployee operation middleware
func (siw *ServerInterfaceWrapper) PatchEmployee(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "employeeID" -------------
	var employeeID int64

	err = runtime.BindStyledParameterWithOptions("simple", "employeeID", chi.URLParam(r, "employeeID"), &employeeID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "employeeID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchEmployee(w, r, employeeID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetShifts operation middleware
func (siw *ServerInterfaceWrapper) GetShifts(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetShiftsParams

	// ------------- Optional query parameter "filter" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "filter", r.URL.Query(), &params.Filter, runtime.BindQueryParameterOptions{Type: "object", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "filter", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetShifts(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateShift operation middleware
func (siw *ServerInterfaceWrapper) CreateShift(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateShift(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetShiftTypes operation middleware
func (siw *ServerInterfaceWrapper) GetShiftTypes(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetShiftTypes(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateShiftType operation middleware
func (siw *ServerInterfaceWrapper) CreateShiftType(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateShiftType(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteShiftType operation middleware
func (siw *ServerInterfaceWrapper) DeleteShiftType(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "shiftTypeID" -------------
	var shiftTypeID int

	err = runtime.BindStyledParameterWithOptions("simple", "shiftTypeID", chi.URLParam(r, "shiftTypeID"), &shiftTypeID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "shiftTypeID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteShiftType(w, r, shiftTypeID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetShiftType operation middleware
func (siw *ServerInterfaceWrapper) GetShiftType(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "shiftTypeID" -------------
	var shiftTypeID int

	err = runtime.BindStyledParameterWithOptions("simple", "shiftTypeID", chi.URLParam(r, "shiftTypeID"), &shiftTypeID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "shiftTypeID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetShiftType(w, r, shiftTypeID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchShiftType operation middleware
func (siw *ServerInterfaceWrapper) PatchShiftType(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "shiftTypeID" -------------
	var shiftTypeID int

	err = runtime.BindStyledParameterWithOptions("simple", "shiftTypeID", chi.URLParam(r, "shiftTypeID"), &shiftTypeID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "shiftTypeID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchShiftType(w, r, shiftTypeID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteShift operation middleware
func (siw *ServerInterfaceWrapper) DeleteShift(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "shiftID" -------------
	var shiftID int

	err = runtime.BindStyledParameterWithOptions("simple", "shiftID", chi.URLParam(r, "shiftID"), &shiftID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "shiftID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteShift(w, r, shiftID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetShift operation middleware
func (siw *ServerInterfaceWrapper) GetShift(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "shiftID" -------------
	var shiftID int

	err = runtime.BindStyledParameterWithOptions("simple", "shiftID", chi.URLParam(r, "shiftID"), &shiftID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "shiftID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetShift(w, r, shiftID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchShift operation middleware
func (siw *ServerInterfaceWrapper) PatchShift(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "shiftID" -------------
	var shiftID int

	err = runtime.BindStyledParameterWithOptions("simple", "shiftID", chi.URLParam(r, "shiftID"), &shiftID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "shiftID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchShift(w, r, shiftID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/employee", wrapper.GetEmployees)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/employee", wrapper.CreateEmployee)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/employee/{employeeID}", wrapper.DeleteEmployee)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/employee/{employeeID}", wrapper.GetEmployee)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/employee/{employeeID}", wrapper.PatchEmployee)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/shift", wrapper.GetShifts)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/shift", wrapper.CreateShift)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/shift-type", wrapper.GetShiftTypes)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/shift-type", wrapper.CreateShiftType)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/shift-type/{shiftTypeID}", wrapper.DeleteShiftType)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/shift-type/{shiftTypeID}", wrapper.GetShiftType)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/shift-type/{shiftTypeID}", wrapper.PatchShiftType)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/shift/{shiftID}", wrapper.DeleteShift)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/shift/{shiftID}", wrapper.GetShift)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/shift/{shiftID}", wrapper.PatchShift)
	})

	return r
}

type BadRequestJSONResponse Error

type ConflictJSONResponse Error

type ForbiddenJSONResponse Error

type NotFoundJSONResponse Error

type UnauthorizedJSONResponse Error

type GetEmployeesRequestObject struct {
	Params GetEmployeesParams
}

type GetEmployeesResponseObject interface {
	VisitGetEmployeesResponse(w http.ResponseWriter) error
}

type GetEmployees200JSONResponse EmployeeList

func (response GetEmployees200JSONResponse) VisitGetEmployeesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetEmployees401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetEmployees401JSONResponse) VisitGetEmployeesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetEmployees403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetEmployees403JSONResponse) VisitGetEmployeesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type CreateEmployeeRequestObject struct {
	Body *CreateEmployeeJSONRequestBody
}

type CreateEmployeeResponseObject interface {
	VisitCreateEmployeeResponse(w http.ResponseWriter) error
}

type CreateEmployee201JSONResponse Employee

func (response CreateEmployee201JSONResponse) VisitCreateEmployeeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateEmployee400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateEmployee400JSONResponse) VisitCreateEmployeeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateEmployee401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateEmployee401JSONResponse) VisitCreateEmployeeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateEmployee403JSONResponse struct{ ForbiddenJSONResponse }

func (response CreateEmployee403JSONResponse) VisitCreateEmployeeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type DeleteEmployeeRequestObject struct {
	EmployeeID int64 `json:"employeeID"`
}

type DeleteEmployeeResponseObject interface {
	VisitDeleteEmployeeResponse(w http.ResponseWriter) error
}

type DeleteEmployee204Response struct {
}

func (response DeleteEmployee204Response) VisitDeleteEmployeeResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteEmployee401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeleteEmployee401JSONResponse) VisitDeleteEmployeeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteEmployee403JSONResponse struct{ ForbiddenJSONResponse }

func (response DeleteEmployee403JSONResponse) VisitDeleteEmployeeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type DeleteEmployee404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteEmployee404JSONResponse) VisitDeleteEmployeeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteEmployee409JSONResponse struct{ ConflictJSONResponse }

func (response DeleteEmployee409JSONResponse) VisitDeleteEmployeeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type GetEmployeeRequestObject struct {
	EmployeeID int64 `json:"employeeID"`
}

type GetEmployeeResponseObject interface {
	VisitGetEmployeeResponse(w http.ResponseWriter) error
}

type GetEmployee200JSONResponse Employee

func (response GetEmployee200JSONResponse) VisitGetEmployeeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetEmployee401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetEmployee401JSONResponse) VisitGetEmployeeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetEmployee403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetEmployee403JSONResponse) VisitGetEmployeeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetEmployee404JSONResponse struct{ NotFoundJSONResponse }

func (response GetEmployee404JSONResponse) VisitGetEmployeeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PatchEmployeeRequestObject struct {
	EmployeeID int64 `json:"employeeID"`
	Body       *PatchEmployeeJSONRequestBody
}

type PatchEmployeeResponseObject interface {
	VisitPatchEmployeeResponse(w http.ResponseWriter) error
}

type PatchEmployee200JSONResponse Employee

func (response PatchEmployee200JSONResponse) VisitPatchEmployeeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PatchEmployee400JSONResponse struct{ BadRequestJSONResponse }

func (response PatchEmployee400JSONResponse) VisitPatchEmployeeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PatchEmployee401JSONResponse struct{ UnauthorizedJSONResponse }

func (response PatchEmployee401JSONResponse) VisitPatchEmployeeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PatchEmployee403JSONResponse struct{ ForbiddenJSONResponse }

func (response PatchEmployee403JSONResponse) VisitPatchEmployeeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type PatchEmployee404JSONResponse struct{ NotFoundJSONResponse }

func (response PatchEmployee404JSONResponse) VisitPatchEmployeeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetShiftsRequestObject struct {
	Params GetShiftsParams
}

type GetShiftsResponseObject interface {
	VisitGetShiftsResponse(w http.ResponseWriter) error
}

type GetShifts200JSONResponse ShiftList

func (response GetShifts200JSONResponse) VisitGetShiftsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetShifts401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetShifts401JSONResponse) VisitGetShiftsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetShifts403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetShifts403JSONResponse) VisitGetShiftsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type CreateShiftRequestObject struct {
	Body *CreateShiftJSONRequestBody
}

type CreateShiftResponseObject interface {
	VisitCreateShiftResponse(w http.ResponseWriter) error
}

type CreateShift201JSONResponse Shift

func (response CreateShift201JSONResponse) VisitCreateShiftResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateShift400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateShift400JSONResponse) VisitCreateShiftResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateShift401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateShift401JSONResponse) VisitCreateShiftResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateShift403JSONResponse struct{ ForbiddenJSONResponse }

func (response CreateShift403JSONResponse) VisitCreateShiftResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetShiftTypesRequestObject struct {
}

type GetShiftTypesResponseObject interface {
	VisitGetShiftTypesResponse(w http.ResponseWriter) error
}

type GetShiftTypes200JSONResponse ShiftTypeList

func (response GetShiftTypes200JSONResponse) VisitGetShiftTypesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetShiftTypes401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetShiftTypes401JSONResponse) VisitGetShiftTypesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetShiftTypes403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetShiftTypes403JSONResponse) VisitGetShiftTypesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type CreateShiftTypeRequestObject struct {
	Body *CreateShiftTypeJSONRequestBody
}

type CreateShiftTypeResponseObject interface {
	VisitCreateShiftTypeResponse(w http.ResponseWriter) error
}

type CreateShiftType201JSONResponse ShiftType

func (response CreateShiftType201JSONResponse) VisitCreateShiftTypeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateShiftType400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateShiftType400JSONResponse) VisitCreateShiftTypeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateShiftType401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateShiftType401JSONResponse) VisitCreateShiftTypeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateShiftType403JSONResponse struct{ ForbiddenJSONResponse }

func (response CreateShiftType403JSONResponse) VisitCreateShiftTypeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type DeleteShiftTypeRequestObject struct {
	ShiftTypeID int `json:"shiftTypeID"`
}

type DeleteShiftTypeResponseObject interface {
	VisitDeleteShiftTypeResponse(w http.ResponseWriter) error
}

type DeleteShiftType204Response struct {
}

func (response DeleteShiftType204Response) VisitDeleteShiftTypeResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteShiftType401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeleteShiftType401JSONResponse) VisitDeleteShiftTypeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteShiftType403JSONResponse struct{ ForbiddenJSONResponse }

func (response DeleteShiftType403JSONResponse) VisitDeleteShiftTypeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type DeleteShiftType404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteShiftType404JSONResponse) VisitDeleteShiftTypeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteShiftType409JSONResponse struct{ ConflictJSONResponse }

func (response DeleteShiftType409JSONResponse) VisitDeleteShiftTypeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type GetShiftTypeRequestObject struct {
	ShiftTypeID int `json:"shiftTypeID"`
}

type GetShiftTypeResponseObject interface {
	VisitGetShiftTypeResponse(w http.ResponseWriter) error
}

type GetShiftType200JSONResponse ShiftType

func (response GetShiftType200JSONResponse) VisitGetShiftTypeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetShiftType401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetShiftType401JSONResponse) VisitGetShiftTypeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetShiftType403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetShiftType403JSONResponse) VisitGetShiftTypeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetShiftType404JSONResponse struct{ NotFoundJSONResponse }

func (response GetShiftType404JSONResponse) VisitGetShiftTypeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PatchShiftTypeRequestObject struct {
	ShiftTypeID int `json:"shiftTypeID"`
	Body        *PatchShiftTypeJSONRequestBody
}

type PatchShiftTypeResponseObject interface {
	VisitPatchShiftTypeResponse(w http.ResponseWriter) error
}

type PatchShiftType200JSONResponse ShiftType

func (response PatchShiftType200JSONResponse) VisitPatchShiftTypeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PatchShiftType400JSONResponse struct{ BadRequestJSONResponse }

func (response PatchShiftType400JSONResponse) VisitPatchShiftTypeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PatchShiftType401JSONResponse struct{ UnauthorizedJSONResponse }

func (response PatchShiftType401JSONResponse) VisitPatchShiftTypeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PatchShiftType403JSONResponse struct{ ForbiddenJSONResponse }

func (response PatchShiftType403JSONResponse) VisitPatchShiftTypeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type PatchShiftType404JSONResponse struct{ NotFoundJSONResponse }

func (response PatchShiftType404JSONResponse) VisitPatchShiftTypeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteShiftRequestObject struct {
	ShiftID int `json:"shiftID"`
}

type DeleteShiftResponseObject interface {
	VisitDeleteShiftResponse(w http.ResponseWriter) error
}

type DeleteShift204Response struct {
}

func (response DeleteShift204Response) VisitDeleteShiftResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteShift401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeleteShift401JSONResponse) VisitDeleteShiftResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteShift403JSONResponse struct{ ForbiddenJSONResponse }

func (response DeleteShift403JSONResponse) VisitDeleteShiftResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type DeleteShift404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteShift404JSONResponse) VisitDeleteShiftResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteShift409JSONResponse struct{ ConflictJSONResponse }

func (response DeleteShift409JSONResponse) VisitDeleteShiftResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type GetShiftRequestObject struct {
	ShiftID int `json:"shiftID"`
}

type GetShiftResponseObject interface {
	VisitGetShiftResponse(w http.ResponseWriter) error
}

type GetShift200JSONResponse Shift

func (response GetShift200JSONResponse) VisitGetShiftResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetShift401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetShift401JSONResponse) VisitGetShiftResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetShift403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetShift403JSONResponse) VisitGetShiftResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetShift404JSONResponse struct{ NotFoundJSONResponse }

func (response GetShift404JSONResponse) VisitGetShiftResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PatchShiftRequestObject struct {
	ShiftID int `json:"shiftID"`
	Body    *PatchShiftJSONRequestBody
}

type PatchShiftResponseObject interface {
	VisitPatchShiftResponse(w http.ResponseWriter) error
}

type PatchShift200JSONResponse Shift

func (response PatchShift200JSONResponse) VisitPatchShiftResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PatchShift400JSONResponse struct{ BadRequestJSONResponse }

func (response PatchShift400JSONResponse) VisitPatchShiftResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PatchShift401JSONResponse struct{ UnauthorizedJSONResponse }

func (response PatchShift401JSONResponse) VisitPatchShiftResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PatchShift403JSONResponse struct{ ForbiddenJSONResponse }

func (response PatchShift403JSONResponse) VisitPatchShiftResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type PatchShift404JSONResponse struct{ NotFoundJSONResponse }

func (response PatchShift404JSONResponse) VisitPatchShiftResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Get all employees
	// (GET /employee)
	GetEmployees(ctx context.Context, request GetEmployeesRequestObject) (GetEmployeesResponseObject, error)
	// Create employee
	// (POST /employee)
	CreateEmployee(ctx context.Context, request CreateEmployeeRequestObject) (CreateEmployeeResponseObject, error)
	// Delete employee
	// (DELETE /employee/{employeeID})
	DeleteEmployee(ctx context.Context, request DeleteEmployeeRequestObject) (DeleteEmployeeResponseObject, error)
	// Get employee
	// (GET /employee/{employeeID})
	GetEmployee(ctx context.Context, request GetEmployeeRequestObject) (GetEmployeeResponseObject, error)
	// Patch employee
	// (PATCH /employee/{employeeID})
	PatchEmployee(ctx context.Context, request PatchEmployeeRequestObject) (PatchEmployeeResponseObject, error)
	// Get all shifts
	// (GET /shift)
	GetShifts(ctx context.Context, request GetShiftsRequestObject) (GetShiftsResponseObject, error)
	// Create shift
	// (POST /shift)
	CreateShift(ctx context.Context, request CreateShiftRequestObject) (CreateShiftResponseObject, error)
	// Get all shift types
	// (GET /shift-type)
	GetShiftTypes(ctx context.Context, request GetShiftTypesRequestObject) (GetShiftTypesResponseObject, error)
	// Create shift type
	// (POST /shift-type)
	CreateShiftType(ctx context.Context, request CreateShiftTypeRequestObject) (CreateShiftTypeResponseObject, error)
	// Delete shift type
	// (DELETE /shift-type/{shiftTypeID})
	DeleteShiftType(ctx context.Context, request DeleteShiftTypeRequestObject) (DeleteShiftTypeResponseObject, error)
	// Get shift type
	// (GET /shift-type/{shiftTypeID})
	GetShiftType(ctx context.Context, request GetShiftTypeRequestObject) (GetShiftTypeResponseObject, error)
	// Patch shift type
	// (PATCH /shift-type/{shiftTypeID})
	PatchShiftType(ctx context.Context, request PatchShiftTypeRequestObject) (PatchShiftTypeResponseObject, error)
	// Delete shift
	// (DELETE /shift/{shiftID})
	DeleteShift(ctx context.Context, request DeleteShiftRequestObject) (DeleteShiftResponseObject, error)
	// Get shift
	// (GET /shift/{shiftID})
	GetShift(ctx context.Context, request GetShiftRequestObject) (GetShiftResponseObject, error)
	// Patch shift
	// (PATCH /shift/{shiftID})
	PatchShift(ctx context.Context, request PatchShiftRequestObject) (PatchShiftResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetEmployees operation middleware
func (sh *strictHandler) GetEmployees(w http.ResponseWriter, r *http.Request, params GetEmployeesParams) {
	var request GetEmployeesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetEmployees(ctx, request.(GetEmployeesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetEmployees")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetEmployeesResponseObject); ok {
		if err := validResponse.VisitGetEmployeesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateEmployee operation middleware
func (sh *strictHandler) CreateEmployee(w http.ResponseWriter, r *http.Request) {
	var request CreateEmployeeRequestObject

	var body CreateEmployeeJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateEmployee(ctx, request.(CreateEmployeeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateEmployee")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateEmployeeResponseObject); ok {
		if err := validResponse.VisitCreateEmployeeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteEmployee operation middleware
func (sh *strictHandler) DeleteEmployee(w http.ResponseWriter, r *http.Request, employeeID int64) {
	var request DeleteEmployeeRequestObject

	request.EmployeeID = employeeID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteEmployee(ctx, request.(DeleteEmployeeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteEmployee")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteEmployeeResponseObject); ok {
		if err := validResponse.VisitDeleteEmployeeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetEmployee operation middleware
func (sh *strictHandler) GetEmployee(w http.ResponseWriter, r *http.Request, employeeID int64) {
	var request GetEmployeeRequestObject

	request.EmployeeID = employeeID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetEmployee(ctx, request.(GetEmployeeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetEmployee")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetEmployeeResponseObject); ok {
		if err := validResponse.VisitGetEmployeeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PatchEmployee operation middleware
func (sh *strictHandler) PatchEmployee(w http.ResponseWriter, r *http.Request, employeeID int64) {
	var request PatchEmployeeRequestObject

	request.EmployeeID = employeeID

	var body PatchEmployeeJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PatchEmployee(ctx, request.(PatchEmployeeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PatchEmployee")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PatchEmployeeResponseObject); ok {
		if err := validResponse.VisitPatchEmployeeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetShifts operation middleware
func (sh *strictHandler) GetShifts(w http.ResponseWriter, r *http.Request, params GetShiftsParams) {
	var request GetShiftsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetShifts(ctx, request.(GetShiftsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetShifts")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetShiftsResponseObject); ok {
		if err := validResponse.VisitGetShiftsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateShift operation middleware
func (sh *strictHandler) CreateShift(w http.ResponseWriter, r *http.Request) {
	var request CreateShiftRequestObject

	var body CreateShiftJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateShift(ctx, request.(CreateShiftRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateShift")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateShiftResponseObject); ok {
		if err := validResponse.VisitCreateShiftResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetShiftTypes operation middleware
func (sh *strictHandler) GetShiftTypes(w http.ResponseWriter, r *http.Request) {
	var request GetShiftTypesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetShiftTypes(ctx, request.(GetShiftTypesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetShiftTypes")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetShiftTypesResponseObject); ok {
		if err := validResponse.VisitGetShiftTypesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateShiftType operation middleware
func (sh *strictHandler) CreateShiftType(w http.ResponseWriter, r *http.Request) {
	var request CreateShiftTypeRequestObject

	var body CreateShiftTypeJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateShiftType(ctx, request.(CreateShiftTypeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateShiftType")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateShiftTypeResponseObject); ok {
		if err := validResponse.VisitCreateShiftTypeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteShiftType operation middleware
func (sh *strictHandler) DeleteShiftType(w http.ResponseWriter, r *http.Request, shiftTypeID int) {
	var request DeleteShiftTypeRequestObject

	request.ShiftTypeID = shiftTypeID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteShiftType(ctx, request.(DeleteShiftTypeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteShiftType")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteShiftTypeResponseObject); ok {
		if err := validResponse.VisitDeleteShiftTypeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetShiftType operation middleware
func (sh *strictHandler) GetShiftType(w http.ResponseWriter, r *http.Request, shiftTypeID int) {
	var request GetShiftTypeRequestObject

	request.ShiftTypeID = shiftTypeID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetShiftType(ctx, request.(GetShiftTypeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetShiftType")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetShiftTypeResponseObject); ok {
		if err := validResponse.VisitGetShiftTypeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PatchShiftType operation middleware
func (sh *strictHandler) PatchShiftType(w http.ResponseWriter, r *http.Request, shiftTypeID int) {
	var request PatchShiftTypeRequestObject

	request.ShiftTypeID = shiftTypeID

	var body PatchShiftTypeJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PatchShiftType(ctx, request.(PatchShiftTypeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PatchShiftType")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PatchShiftTypeResponseObject); ok {
		if err := validResponse.VisitPatchShiftTypeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteShift operation middleware
func (sh *strictHandler) DeleteShift(w http.ResponseWriter, r *http.Request, shiftID int) {
	var request DeleteShiftRequestObject

	request.ShiftID = shiftID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteShift(ctx, request.(DeleteShiftRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteShift")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteShiftResponseObject); ok {
		if err := validResponse.VisitDeleteShiftResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetShift operation middleware
func (sh *strictHandler) GetShift(w http.ResponseWriter, r *http.Request, shiftID int) {
	var request GetShiftRequestObject

	request.ShiftID = shiftID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetShift(ctx, request.(GetShiftRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetShift")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetShiftResponseObject); ok {
		if err := validResponse.VisitGetShiftResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PatchShift operation middleware
func (sh *strictHandler) PatchShift(w http.ResponseWriter, r *http.Request, shiftID int) {
	var request PatchShiftRequestObject

	request.ShiftID = shiftID

	var body PatchShiftJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PatchShift(ctx, request.(PatchShiftRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PatchShift")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PatchShiftResponseObject); ok {
		if err := validResponse.VisitPatchShiftResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+RaW0/cOBT+K5F3HwMTLlpt560tUCG1gBZ42G3RyCQn4CqxU9vDdhblv69s5+LcxqHM",
	"BcTbkPjYx+f7zjU8opClGaNApUDTR8RBZIwK0H98wNFf8GMOQqq/QkYlUP0TZ1lCQiwJo5PvglH1TIT3",
	"kGL163cOMZqi3yb11hPzVkyOOWcc5XnuowhEyEmmNkFTpF94hHrcnOhlmONUTG5ZtEC5jz4yGick3IAm",
	"5Unf0PQb8s5vv0MovXssPA4JlhB5EZZYqXTC+C2JIqDr1+mUinkck5AAlV7GyQNJ4A6E0uKMyRM2p9H6",
	"lShMQZn0Yn1i7qNriufynnHyH2xAg8Zp6nUhoTY8ggxzmQKVl/eMaw3oPEnwbQJoKvkcfJRxlgGXxLCb",
	"aIXlIgM0RYRKuAOurkRxCtYbITmhd/o0RU3C1UW/Kuli6Y1fLmXaQGqP4zRL2AL0PjhJzmM0/frYOj/k",
	"oOg0w1pX+InTTKmK9oP9w53gYGc/uAreTff2p/t//oN8FDOeqqUowhJ2JEkB+W0dlb1KK7iM3LZX7hcW",
	"qQ4iVP5xWB9imShjghhIlp9xUayrTpgL4C6hawG8EOjavMfYDi4VSHzAAlB+Y2Gjn0zbqOBQkgcb/1vG",
	"EsBUaR8TLuRsgB8+SkkUJVC9b7Ovs15AyGg0G8c36+ym5DL6fdQUa5JwvLH8tm1qcs0MVQau2MOU0QKK",
	"IbMBIrqk844pbLxPSCIN+4YQH9jfYsAvWKBJGicpEpISOW5nFscCRq5tcc2hRr6EU5+JKQdawVRC2vwx",
	"hmeoPghzjnWil0zipBER94JgDNa1ihdYhvdPc+1nA+uKBp33T/aM5eFi1Z5TW7NKpyuJISNzzJjI3xv5",
	"dOnQgT5kETSz7PGXi8/nfx8fz87Or2Yn59dnR33pNAUh8F1btLihVQn5juhd7uMbTfo0b+bKrVYvl/ck",
	"lhsvXcCqmcYQrFW29DiMusbMPF++pb7wlVqo/CiLVn25FdQxWsW6iKn/7HA9KlJ+Q7E+gwuJ5Vw0L5kl",
	"mFKItAYJSPUL0xCSBNwk1+cM8umptYh14U4QKakyG12x1lyY9dMl7wsv9u3sM/3Sps1tB+8+VHqoXWYx",
	"Z2kfXs5SQUtL9kuyLQu6s8+66pI2LiNEKtr+QhWj4VhFCWNi5GrrF73nQPEy5NWrR3orkFwVUfq5SW54",
	"9zr+NM8YlzCX50q1/8pIVeahVRNL7TtArifYs+7OnSUKpJgkvaXqEK6cJa1aC0cpoZMUU3wHfFKVCP6Y",
	"+sacX+zaxU7JEBoz09naY6b3F6feZQYhiYv5lRcz7l1efzoi5977i1N1PJFav8bDB+DC7BDsBrt7OhZm",
	"QHFG0BQd7Aa7B8hHGZb32jwTu+C5MwFTmU+feBqhKfoEsix2hJbkOAUJXOjk2Zqflgu92CQbH8HPLNF1",
	"rwGHqGU/5sAXZe03RdXakYO5ZiudmxxpTYz3g2B1U0C74ewZBl7OwxCEnoEeBntDu1XqTZrDQyV04Baq",
	"Z7x63DhPU8wXBhoPJ4kHFj4S3wm7UkA3ps3rQdYEo+OazsXU+wOLFis3YBH5ekx4Bv9WNzBjbduNFG3y",
	"DsB7K9ev93NAqVXRahjAAjdg1jeLrRDDGNuzI1WXFrlfe//ksfx1epSbWKQK7y5njvRzizOteKD9W0WX",
	"2r3rnTvA2i7fqZ9TQkk6T9F0rye/dH3+sBtCK/zMbaKNgaEkDt0S1VcTLfDOLVB9f2rCbUBxwO07w/tL",
	"QjPYiINvOno/mRedcO/COCtrqybKuuR6ITivL8eYwnJZII8JJJEnmWfs5E40wWYTTTH2ecmJ5nkc1hCN",
	"SEyinP4NBS3dTTgLUrNqndWoPVpZbyCrpwYvtQ4VJSYlqAZFVwVqphjrCQ321G+g9tRKbr7wLGY3PVBq",
	"fV5pySkKLNsMqHx6pxyFL3Xsq0Wmu5n1OlM1MXnRDuXJwhgNm5pPCqNcS89y1uhe1mBrqYspjbfkZ2ac",
	"NeRrWrHX7HD6BkMMabre5FGUBhnV6tkMcleN1t5Ly8bn93YWcm+ju3MD7btj6jZBDDbk0q+upxuD7LK+",
	"blvorjGdDHZyltvrXk5sp5kbm1TeSD/3hCRU5J/xuWc8qTeUc95Quult5ZYmmW2hFWygL3udiaW/HXel",
	"kw3iuKY04kghW88ew6q9paTRNyrIq2ftAPxFf4JvfO9sjav1/2n1Cj1gg5UlVD4aFqomWjbjHcurft2W",
	"MXkwv8n/DwAA//+pn5dJ7DQAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
